"""
totp.py — `/api/v1/me/2fa/*`. Self-service TOTP enrolment for the caller's
own account, and nobody else's — same self-scoping discipline as
`routers/me.py`, which this file sits beside (kept separate because `me.py`
is already 576 lines before this).

Optional per person always; optional per ORG in the sense that an org_owner
can flip `staging.org_security.tfa_enforced` (see `routers/org_security.py`)
to require it of every member of THEIR org — Aekam never mandates it
platform-wide. Login (`auth_router.py`) is what actually reads that flag;
this file only ever enrols, confirms, disables and re-issues recovery codes
for the account making the request.

ENROLMENT NEVER TOUCHES THE DATABASE UNTIL A CODE IS CONFIRMED. The secret
generated by `/setup` travels to the client inside a short-lived, signed
"setup token" (same `JWT_SECRET` as a session, 10-minute expiry, a `purpose`
claim `auth_router.require_user` already refuses everywhere else in the
product) rather than as a pending row. See `migrations/208_user_totp.sql`
for why: `org_security.py`'s lockout count trusts that a row in
`staging.user_totp` means a WORKING authenticator, and an abandoned setup
must leave nothing behind for that count to stay honest.
"""
import logging

from fastapi import APIRouter, Depends, HTTPException, Request
from pydantic import BaseModel

import jwt as pyjwt
import segno

from auth_router import (
    JWT_ALGORITHM, JWT_SECRET, _row_get, _verify_password, require_user,
)
from db import get_pool
from limiter import limiter
from services import totp as totp_service
from services.audit import emit as audit

log = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/me/2fa", tags=["two-factor"])

SETUP_TOKEN_TTL_MINUTES = 10


# ── Storage probe — mirrors org_security.py's pattern ─────────────────────────

_table_present: bool | None = None


async def _storage_ready(pool) -> bool:
    global _table_present
    if _table_present:
        return True
    _table_present = bool(await pool.fetchval("SELECT to_regclass('staging.user_totp')"))
    return _table_present


def _require_storage(ready: bool) -> None:
    if not ready:
        raise HTTPException(
            503,
            "Two-factor authentication is not available yet: "
            "staging.user_totp does not exist. Apply "
            "migrations/208_user_totp.sql.",
        )


# ── Setup token — a JWT that is NOT a session ─────────────────────────────────
# `purpose` is the whole mechanism: `auth_router.require_user` rejects any
# token carrying it, on every route in the product, so this cannot be used
# as a bearer token or a cookie no matter where it is replayed.

def _make_setup_token(user_id: str, secret: str) -> str:
    from datetime import datetime, timedelta, timezone
    now = datetime.now(timezone.utc)
    claims = {
        "sub": user_id,
        "purpose": "totp_setup",
        "secret": secret,
        "iat": now,
        "exp": now + timedelta(minutes=SETUP_TOKEN_TTL_MINUTES),
    }
    return pyjwt.encode(claims, JWT_SECRET, algorithm=JWT_ALGORITHM)


def _decode_setup_token(token: str, expected_user_id: str) -> str:
    """Returns the pending secret, or raises 400 naming why."""
    try:
        claims = pyjwt.decode(token, JWT_SECRET, algorithms=[JWT_ALGORITHM])
    except pyjwt.PyJWTError:
        raise HTTPException(400, "This setup session has expired. Start again.")
    if claims.get("purpose") != "totp_setup" or claims.get("sub") != expected_user_id:
        raise HTTPException(400, "This setup session is not valid. Start again.")
    secret = claims.get("secret")
    if not secret:
        raise HTTPException(400, "This setup session is not valid. Start again.")
    return secret


# ── Status ──────────────────────────────────────────────────────────────────

@router.get("")
async def get_status(user=Depends(require_user)):
    pool = await get_pool()
    ready = await _storage_ready(pool)
    if not ready:
        return {"enabled": False, "storage_ready": False, "required_by_org": []}

    row = await pool.fetchrow(
        "SELECT created_at FROM staging.user_totp WHERE user_id=$1", user["user_id"],
    )
    remaining = 0
    if row:
        remaining = await pool.fetchval(
            "SELECT COUNT(*) FROM staging.user_totp_recovery_codes "
            "WHERE user_id=$1 AND used_at IS NULL",
            user["user_id"],
        ) or 0

    # Orgs this person belongs to that require 2FA — informational, so the
    # UI can say WHY enrolling isn't really optional for this person even
    # though the product-wide default is.
    required_by = await pool.fetch(
        "SELECT o.id::text AS org_id, o.name AS org_name "
        "FROM staging.user_roles ur "
        "JOIN staging.organisations o ON o.id = ur.org_id "
        "JOIN staging.org_security os ON os.org_id = ur.org_id "
        "WHERE ur.user_id=$1 AND ur.role_code IN ('org_owner','org_admin','org_member') "
        "AND os.tfa_enforced = TRUE",
        user["user_id"],
    )

    return {
        "enabled": bool(row),
        "storage_ready": True,
        "enrolled_at": row["created_at"].isoformat() if row else None,
        "recovery_codes_remaining": remaining,
        "required_by_org": [dict(r) for r in required_by],
    }


# ── Setup ───────────────────────────────────────────────────────────────────

@router.post("/setup")
@limiter.limit("10/minute")
async def setup(request: Request, user=Depends(require_user)):
    """Generate a new secret. Nothing is written until /confirm succeeds."""
    pool = await get_pool()
    _require_storage(await _storage_ready(pool))

    secret = totp_service.generate_secret()
    uri = totp_service.provisioning_uri(secret, user["email"])
    setup_token = _make_setup_token(user["user_id"], secret)
    qr_svg = segno.make(uri).svg_data_uri(scale=5, border=2)

    return {
        "setup_token": setup_token,
        "secret": secret,
        "otpauth_uri": uri,
        "qr_svg_data_uri": qr_svg,
        "expires_in_minutes": SETUP_TOKEN_TTL_MINUTES,
    }


class ConfirmBody(BaseModel):
    setup_token: str
    code: str


@router.post("/confirm")
@limiter.limit("10/minute")
async def confirm(request: Request, body: ConfirmBody, user=Depends(require_user)):
    pool = await get_pool()
    _require_storage(await _storage_ready(pool))

    secret = _decode_setup_token(body.setup_token, user["user_id"])
    ok, step = totp_service.verify_code(secret, body.code, last_used_step=None)
    if not ok:
        raise HTTPException(400, "Incorrect code. Check the time on your device and try again.")

    codes = totp_service.generate_recovery_codes()
    encrypted = totp_service.encrypt_secret(secret)

    async with pool.acquire() as conn:
        async with conn.transaction():
            await conn.execute(
                "INSERT INTO staging.user_totp (user_id, secret, last_used_step, updated_at) "
                "VALUES ($1, $2, $3, NOW()) "
                "ON CONFLICT (user_id) DO UPDATE SET "
                "secret=EXCLUDED.secret, last_used_step=EXCLUDED.last_used_step, "
                "updated_at=NOW()",
                user["user_id"], encrypted, step,
            )
            # A re-enrolment (lost device) must not leave the OLD device's
            # unused codes still redeemable against the new secret.
            await conn.execute(
                "DELETE FROM staging.user_totp_recovery_codes "
                "WHERE user_id=$1 AND used_at IS NULL",
                user["user_id"],
            )
            # A loop of `execute`, not `executemany` — nothing else in this
            # codebase uses executemany, and ten single-row inserts inside
            # one transaction cost nothing extra here.
            for c in codes:
                await conn.execute(
                    "INSERT INTO staging.user_totp_recovery_codes (user_id, code_hash) "
                    "VALUES ($1, $2)",
                    user["user_id"], totp_service.hash_recovery_code(c),
                )

    audit("auth.2fa_enabled", request, user_id=user["user_id"], severity="warn")

    return {
        "status": "enabled",
        "recovery_codes": [totp_service.format_recovery_code(c) for c in codes],
    }


# ── Disable ─────────────────────────────────────────────────────────────────

class DisableBody(BaseModel):
    password: str


@router.post("/disable")
@limiter.limit("5/minute")
async def disable(request: Request, body: DisableBody, user=Depends(require_user)):
    """Turn 2FA off for this account. Requires the current password — a
    session alone is not enough to remove a second factor from itself."""
    pool = await get_pool()
    _require_storage(await _storage_ready(pool))

    full = await pool.fetchrow(
        "SELECT salt, password_hash, is_system FROM users WHERE user_id=$1", user["user_id"],
    )
    if (
        not full or not full["salt"] or not full["password_hash"]
        or _row_get(full, "is_system")
        or not _verify_password(body.password, full["salt"], full["password_hash"])
    ):
        raise HTTPException(401, "Incorrect password.")

    blocking = await pool.fetch(
        "SELECT o.name AS org_name FROM staging.user_roles ur "
        "JOIN staging.organisations o ON o.id = ur.org_id "
        "JOIN staging.org_security os ON os.org_id = ur.org_id "
        "WHERE ur.user_id=$1 AND ur.role_code IN ('org_owner','org_admin','org_member') "
        "AND os.tfa_enforced = TRUE",
        user["user_id"],
    )
    if blocking:
        names = ", ".join(r["org_name"] for r in blocking)
        raise HTTPException(
            409,
            f"Two-factor authentication cannot be disabled: {names} requires "
            "it for every member. Ask that organisation's owner to turn off "
            "enforcement first, or this account will be unable to sign in.",
        )

    async with pool.acquire() as conn:
        async with conn.transaction():
            await conn.execute("DELETE FROM staging.user_totp WHERE user_id=$1", user["user_id"])
            await conn.execute(
                "DELETE FROM staging.user_totp_recovery_codes WHERE user_id=$1",
                user["user_id"],
            )

    audit("auth.2fa_disabled", request, user_id=user["user_id"], severity="warn")
    return {"status": "disabled"}


# ── Recovery codes ────────────────────────────────────────────────────────────

class RegenerateBody(BaseModel):
    code: str


@router.post("/recovery-codes/regenerate")
@limiter.limit("5/minute")
async def regenerate_recovery_codes(
    request: Request, body: RegenerateBody, user=Depends(require_user),
):
    pool = await get_pool()
    _require_storage(await _storage_ready(pool))

    row = await pool.fetchrow(
        "SELECT secret, last_used_step FROM staging.user_totp WHERE user_id=$1",
        user["user_id"],
    )
    if not row:
        raise HTTPException(409, "Two-factor authentication is not enabled on this account.")

    secret = totp_service.decrypt_secret(row["secret"])
    ok, step = totp_service.verify_code(secret, body.code, row["last_used_step"])
    if not ok:
        raise HTTPException(400, "Incorrect code.")

    codes = totp_service.generate_recovery_codes()
    async with pool.acquire() as conn:
        async with conn.transaction():
            await conn.execute(
                "UPDATE staging.user_totp SET last_used_step=$2, updated_at=NOW() "
                "WHERE user_id=$1", user["user_id"], step,
            )
            await conn.execute(
                "DELETE FROM staging.user_totp_recovery_codes "
                "WHERE user_id=$1 AND used_at IS NULL",
                user["user_id"],
            )
            # A loop of `execute`, not `executemany` — nothing else in this
            # codebase uses executemany, and ten single-row inserts inside
            # one transaction cost nothing extra here.
            for c in codes:
                await conn.execute(
                    "INSERT INTO staging.user_totp_recovery_codes (user_id, code_hash) "
                    "VALUES ($1, $2)",
                    user["user_id"], totp_service.hash_recovery_code(c),
                )

    audit("auth.2fa_recovery_codes_regenerated", request, user_id=user["user_id"], severity="warn")
    return {"recovery_codes": [totp_service.format_recovery_code(c) for c in codes]}
