/**
 * tabLabels.js — the Devanagari name for every module tab.
 *
 * Ported verbatim from `design-reference/Kartavaya Redesign/Data.jsx` TAB_HI,
 * which is what the runnable mockups render. The build was showing bare
 * lowercase ids (`follow-ups`, `web-forms`) with no Devanagari at all, on a
 * product whose whole type system exists to set the two scripts together.
 *
 * A missing key renders the English alone rather than a placeholder — a tab with
 * no Devanagari is a gap to fill, not a thing to mark.
 */
export const TAB_HI = {
  today: 'आज',
  clients: 'ग्राहक',
  contacts: 'संपर्क',
  deals: 'सौदे',
  kanban: 'फलक',
  pipeline: 'प्रवाह',
  'follow-ups': 'अनुसरण',
  labels: 'नाम',
  activities: 'क्रिया',
  reports: 'रिपोर्ट',
  automations: 'स्वचालन',
  territories: 'क्षेत्र',
  fields: 'क्षेत्र',
  'web-forms': 'प्रपत्र',
  approvals: 'सम्मति',
  documents: 'दस्तावेज़',
  dedupe: 'शोधन',
  invoices: 'बीजक',
  products: 'वस्तु',
  expenses: 'व्यय',
  payables: 'देय',
  contracts: 'अनुबंध',
  'e-sign': 'हस्ताक्षर',
  recurring: 'आवर्ती',
  bank: 'बैंक',
  timesheet: 'समय',
  stats: 'आँकड़े',
  employees: 'कर्मचारी',
  attendance: 'उपस्थिति',
  shifts: 'पारी',
  leaves: 'अवकाश',
  recruitment: 'भर्ती',
  announcements: 'सूचना',
  departments: 'विभाग',
  holidays: 'छुट्टी',
  performance: 'प्रदर्शन',
  assets: 'संपत्ति',
  exits: 'निर्गम',
  dashboard: 'मुख्य',
  structures: 'संरचना',
  payroll: 'वेतन',
  payslips: 'पर्ची',
  loans: 'ऋण',
  statutory: 'अनुपालन',
  orders: 'आदेश',
  stock: 'भंडार',
  targets: 'लक्ष्य',
  customers: 'ग्राहक',
  campaigns: 'अभियान',
  ads: 'विज्ञापन',
  sequences: 'क्रम',
  templates: 'साँचा',
  unsubscribes: 'निकास',
  events: 'घटना',
  overview: 'सारांश',
  revenue: 'राजस्व',
  hr: 'मानव',
  sales: 'विक्रय',
  dashboards: 'पटल',
  pivot: 'सारणी',
  channels: 'माध्यम',
  whatsapp: 'व्हाट्सएप',
  create: 'नया',
  conversations: 'बातचीत',
  'auto-replies': 'स्वउत्तर',
  accounts: 'खाता',
  appearance: 'रूप',
  typography: 'अक्षर',
  layout: 'ढाँचा',
  language: 'भाषा',
  notifications: 'सूचना',
  data: 'गोपनीयता',
  profile: 'रूपरेखा',
  billing: 'बीजक',
  modules: 'खंड',
  security: 'सुरक्षा',
  'danger zone': 'संकट',
  active: 'सक्रिय',
  queue: 'प्रतीक्षा',
  history: 'इतिहास',
  users: 'लोग',
  orgs: 'संस्था',
  costs: 'व्यय',
  members: 'सदस्य',
  matrix: 'सारणी',
  'role levels': 'स्तर',
  'denied states': 'निषेध',
  'client portal': 'ग्राहक',
  'module rules': 'नियम',
  invitations: 'निमंत्रण',
  'support access': 'सहायता',
  'audit log': 'अभिलेख',
  projects: 'परियोजना',
  skills: 'कौशल',
  content: 'सामग्री',
  generate: 'सहायक',
  'data catalog': 'सूची',
  'data runs': 'प्रयोग',
  credits: 'श्रेय',
  knowledge: 'ज्ञान',
  publish: 'प्रकाशन',
  brand: 'ब्रांड',
  chat: 'संवाद',
  table: 'सूची',
  calendar: 'पंचांग',
  timeline: 'कालरेखा',
  workload: 'भार',
  priority: 'प्राथमिकता',
  mytasks: 'मेरे कार्य',
};

/** English label for a tab id: `follow-ups` reads as `follow ups`. */
export const tabEn = (id) => String(id).replace(/-/g, ' ');
