/**
 * emojiData.js — the picker's vocabulary. LAZILY LOADED; never import this
 * statically.
 *
 * `docs/proposals/09-sanvaad-design-system.html` §4 settles four things about
 * the picker and three of them are decisions about this file:
 *
 *  · NATIVE EMOJI, NO IMAGE SPRITES. "Every target platform renders them. A
 *    sprite sheet is ~400 KB and a licence question for nothing." So the data
 *    here is characters and words, and the font does the drawing.
 *  · SEARCH IS KEYWORD, NOT FUZZY. Every entry carries a space-separated
 *    keyword string and the search is a substring test over it. Fuzzy matching
 *    on a list this size returns 😴 for "sad" and teaches people to scroll
 *    instead of type.
 *  · IT MUST NOT SIT IN THE MAIN BUNDLE. `EmojiPicker.jsx` reaches this through
 *    `import('./emojiData')`, which Vite emits as its own chunk, so the cost is
 *    paid by the first reader who opens the picker and by nobody else. A static
 *    import anywhere — including from a test — puts it back in the entry chunk
 *    and silently undoes that. `sanvaadEmoji.test.js` imports it dynamically for
 *    the same reason.
 *  · THE EXISTING ENDPOINT IS UNCHANGED. `samvada_message_reactions.emoji` is
 *    already free text, so nothing here needs a migration.
 *
 * HOW LONG THIS LIST IS, HONESTLY. Proposal 09 costs the picker against "a
 * curated ~1,500-emoji list with keywords". This is ~460, hand-authored, and the
 * shortfall is deliberate rather than unfinished: the missing thousand are
 * overwhelmingly flags, skin-tone and gender variants of entries already here,
 * and the long tail of Unicode that a chartered-accountancy firm's channel will
 * never reach for. Every one of them is still POSTABLE — the composer takes any
 * character the reader's own OS keyboard emits, and the reaction column is free
 * text — they are simply not offered in the grid. If the tail is ever wanted,
 * this file grows and nothing else changes.
 *
 * KEYWORDS ARE BRITISH AND AMERICAN WHERE THEY DIVERGE ('colour color'), and
 * they include the Indian-English word where one exists ('rupee', 'namaste',
 * 'diya'), because the people typing into this box are in India and 'lakh' is
 * not a synonym anybody has to be taught.
 *
 * The name is duplicated into the keyword string on purpose, so a caller can
 * match on `keywords` alone and never has to concatenate two fields.
 */

/**
 * One category. `id` is stable and is what `localStorage` and the tab strip key
 * on; `label` is what a reader sees.
 *
 * FLAGS ARE ABSENT and that is a decision, not an omission. There are ~260 of
 * them, they are half the weight of a full emoji list, they render as two-letter
 * boxes on Windows (which is most of this product's desktop use), and a national
 * flag posted into a work channel is a category of argument nobody asked this
 * module to host.
 */
export const CATEGORIES = [
  {
    id: 'people',
    label: 'Smileys & people',
    emoji: [
      ['😀', 'grin grinning smile happy face'],
      ['😃', 'smiley happy joy face open mouth'],
      ['😄', 'smile happy joy laugh face'],
      ['😁', 'beaming grin happy face teeth'],
      ['😆', 'laughing satisfied happy haha face'],
      ['😅', 'sweat smile relief phew nervous laugh'],
      ['🤣', 'rofl rolling laughing floor lol'],
      ['😂', 'joy tears laugh crying lol funny'],
      ['🙂', 'slight smile happy face'],
      ['🙃', 'upside down silly sarcasm irony'],
      ['😉', 'wink flirt joke face'],
      ['😊', 'blush smile happy shy pleased'],
      ['😇', 'innocent halo angel saint'],
      ['🥰', 'love hearts adore smiling face'],
      ['😍', 'heart eyes love crush adore'],
      ['🤩', 'star struck excited amazed wow'],
      ['😘', 'kiss blowing love face'],
      ['😗', 'kissing face whistle'],
      ['😚', 'kissing closed eyes'],
      ['😋', 'yum tasty tongue delicious savouring savoring'],
      ['😛', 'tongue out playful cheeky'],
      ['😜', 'wink tongue joke playful crazy'],
      ['🤪', 'zany goofy silly wild crazy'],
      ['😝', 'squint tongue playful yuck'],
      ['🤑', 'money mouth rich dollar cash rupee'],
      ['🤗', 'hug hugging warm welcome'],
      ['🤭', 'hand over mouth oops giggle whoops'],
      ['🤫', 'shush quiet silence secret'],
      ['🤔', 'thinking hmm consider doubt wonder'],
      ['🫡', 'salute respect yes sir acknowledged on it'],
      ['🤐', 'zipper mouth quiet secret sealed'],
      ['🤨', 'raised eyebrow suspicious sceptical skeptical doubt'],
      ['😐', 'neutral blank meh straight face'],
      ['😑', 'expressionless blank unimpressed'],
      ['😶', 'no mouth speechless silent blank'],
      ['🫥', 'dotted line invisible hiding gone'],
      ['😏', 'smirk smug sly knowing'],
      ['😒', 'unamused annoyed unimpressed side eye'],
      ['🙄', 'eye roll rolling eyes exasperated whatever'],
      ['😬', 'grimace awkward eek yikes nervous'],
      ['🤥', 'lying pinocchio liar nose'],
      ['🫠', 'melting hot overwhelmed dissolve'],
      ['😌', 'relieved calm content peaceful'],
      ['😔', 'pensive sad down disappointed'],
      ['😪', 'sleepy tired snot bubble'],
      ['😴', 'sleeping asleep zzz tired bored'],
      ['😷', 'mask sick ill covid face mask'],
      ['🤒', 'thermometer sick fever ill unwell'],
      ['🤕', 'bandage hurt injured head'],
      ['🤢', 'nauseated sick green disgust'],
      ['🤮', 'vomit sick throw up disgust'],
      ['🤧', 'sneeze tissue cold flu'],
      ['🥵', 'hot heat sweating overheated summer'],
      ['🥶', 'cold freezing ice winter'],
      ['🥴', 'woozy dizzy drunk confused'],
      ['😵', 'dizzy knocked out spiral confused'],
      ['🤯', 'mind blown exploding head shocked wow'],
      ['🥳', 'party celebrate birthday hat congratulations'],
      ['🥸', 'disguise glasses moustache mustache incognito'],
      ['😎', 'sunglasses cool smug confident'],
      ['🤓', 'nerd glasses geek study clever'],
      ['🧐', 'monocle inspect scrutinise scrutinize examine'],
      ['😕', 'confused unsure puzzled'],
      ['🫤', 'diagonal mouth unsure meh uncomfortable'],
      ['😟', 'worried concerned anxious'],
      ['🙁', 'slight frown sad disappointed'],
      ['😮', 'open mouth surprised shock wow'],
      ['😯', 'hushed surprised stunned quiet'],
      ['😲', 'astonished shocked gasp amazed'],
      ['😳', 'flushed embarrassed blush shocked'],
      ['🥺', 'pleading puppy eyes please beg'],
      ['🥹', 'holding back tears touched emotional proud'],
      ['😦', 'frowning open mouth shock'],
      ['😨', 'fearful scared afraid worried'],
      ['😰', 'anxious sweat nervous worried'],
      ['😥', 'sad relieved disappointed phew'],
      ['😢', 'cry sad tear upset'],
      ['😭', 'sobbing crying loud sad bawling'],
      ['😱', 'scream fear shock horror'],
      ['😖', 'confounded frustrated distressed'],
      ['😣', 'persevere struggle effort strain'],
      ['😞', 'disappointed sad let down'],
      ['😓', 'downcast sweat stressed hard work'],
      ['😩', 'weary tired exhausted fed up'],
      ['😫', 'tired exhausted done fed up'],
      ['🥱', 'yawn bored tired sleepy'],
      ['😤', 'triumph steam nose determined annoyed'],
      ['😡', 'angry rage mad furious red'],
      ['😠', 'angry annoyed mad cross'],
      ['🤬', 'cursing swearing symbols angry furious'],
      ['💀', 'skull dead died rip morbid'],
      ['💩', 'poop rubbish garbage bad awful'],
      ['🤡', 'clown joke silly ridiculous'],
      ['👻', 'ghost boo spooky halloween'],
      ['👽', 'alien ufo extraterrestrial'],
      ['🤖', 'robot bot ai automation machine'],
      ['🎃', 'pumpkin halloween jack lantern'],
      ['😺', 'cat happy smile'],
      ['😹', 'cat joy laugh tears'],
      ['😻', 'cat heart eyes love'],
      ['🙈', 'see no evil monkey hide embarrassed'],
      ['🙉', 'hear no evil monkey ignore'],
      ['🙊', 'speak no evil monkey quiet secret'],
      ['👶', 'baby infant child newborn'],
      ['🧒', 'child kid young'],
      ['👩', 'woman lady female'],
      ['👨', 'man male guy'],
      ['🧑', 'person adult someone'],
      ['👵', 'old woman grandmother elderly'],
      ['👴', 'old man grandfather elderly'],
      ['👮', 'police officer cop law'],
      ['🕵️', 'detective spy investigate audit'],
      ['👷', 'construction worker builder site'],
      ['🧑‍⚖️', 'judge court law justice'],
      ['🧑‍🌾', 'farmer agriculture rural'],
      ['🧑‍🍳', 'cook chef kitchen'],
      ['🧑‍🔧', 'mechanic engineer repair fix'],
      ['🧑‍💼', 'office worker business professional'],
      ['🧑‍🔬', 'scientist research lab'],
      ['🧑‍💻', 'developer programmer coder technologist'],
      ['🧑‍🏫', 'teacher professor train instructor'],
      ['🧑‍🎓', 'student graduate learn'],
      ['🧑‍⚕️', 'doctor nurse health medical'],
      ['🙋', 'raising hand question volunteer here'],
      ['🙆', 'ok gesture yes correct arms'],
      ['🙅', 'no gesture stop refuse forbidden'],
      ['💁', 'information tipping hand sassy help desk'],
      ['🤷', 'shrug dunno no idea whatever'],
      ['🤦', 'facepalm oh no disbelief embarrassed'],
      ['🙇', 'bow sorry apology respect please'],
      ['🧘', 'meditate yoga calm zen breathe'],
      ['🚶', 'walking walk pedestrian'],
      ['🏃', 'running run hurry sprint'],
      ['💃', 'dancing dance celebrate'],
      ['🕺', 'dancing man dance celebrate'],
      ['👯', 'bunny ears partying twins celebrate'],
      ['🧑‍🤝‍🧑', 'people holding hands team together partners'],
      ['👪', 'family parents children'],
      ['🫂', 'hug people embrace support comfort'],
    ],
  },
  {
    id: 'gestures',
    label: 'Gestures',
    emoji: [
      ['👍', 'thumbs up yes agree good approve like ok'],
      ['👎', 'thumbs down no disagree bad reject dislike'],
      ['👌', 'ok perfect fine good'],
      ['🤌', 'pinched fingers italian what gesture'],
      ['🤏', 'pinch small little tiny bit'],
      ['✌️', 'peace victory two'],
      ['🤞', 'fingers crossed luck hope wish'],
      ['🫰', 'fingers crossed money snap heart'],
      ['🤟', 'love you sign hand'],
      ['🤘', 'rock on horns metal'],
      ['🤙', 'call me shaka hang loose'],
      ['👈', 'point left back previous'],
      ['👉', 'point right next forward this'],
      ['👆', 'point up above this attention'],
      ['👇', 'point down below this'],
      ['☝️', 'point up index one attention'],
      ['✋', 'raised hand stop high five'],
      ['🤚', 'raised back of hand stop'],
      ['🖐️', 'hand fingers splayed stop five'],
      ['🖖', 'vulcan salute spock live long'],
      ['👋', 'wave hello hi bye greeting'],
      ['🤝', 'handshake deal agree partnership signed'],
      ['🙏', 'pray thanks please namaste grateful thank you'],
      ['✍️', 'writing hand sign note pen'],
      ['💪', 'muscle strong flex power'],
      ['🦾', 'mechanical arm strong prosthetic'],
      ['👏', 'clap applause well done bravo praise'],
      ['🙌', 'raising hands celebrate praise hooray yay'],
      ['👐', 'open hands hug welcome'],
      ['🤲', 'palms up together pray request dua'],
      ['🫱', 'rightwards hand offer shake'],
      ['🫲', 'leftwards hand offer shake'],
      ['🫳', 'palm down hand drop'],
      ['🫴', 'palm up hand offer here'],
      ['✊', 'fist raised solidarity power'],
      ['👊', 'fist bump punch bro'],
      ['🖕', 'middle finger rude offensive'],
      ['💅', 'nail polish manicure whatever unbothered'],
      ['🦵', 'leg kick limb'],
      ['👀', 'eyes look watching seen reviewing'],
      ['👁️', 'eye look see watch'],
      ['🧠', 'brain mind smart think idea'],
      ['🫀', 'anatomical heart organ health'],
      ['👂', 'ear listen hear'],
      ['👃', 'nose smell'],
      ['👅', 'tongue taste lick'],
      ['🦷', 'tooth dental teeth'],
    ],
  },
  {
    id: 'work',
    label: 'Work',
    emoji: [
      ['📌', 'pin pinned important stick note'],
      ['📍', 'round pin location place here'],
      ['📎', 'paperclip attachment attach clip file'],
      ['🖇️', 'linked paperclips attachments link'],
      ['📁', 'folder directory file'],
      ['📂', 'open folder directory files'],
      ['🗂️', 'card index dividers organise organize files'],
      ['📄', 'page document file paper sheet'],
      ['📃', 'page curl document paper'],
      ['📑', 'bookmark tabs index sections'],
      ['📊', 'bar chart graph data analytics report'],
      ['📈', 'chart increasing up growth profit rising'],
      ['📉', 'chart decreasing down loss falling'],
      ['🗒️', 'notepad spiral notes memo'],
      ['🗓️', 'calendar spiral date schedule'],
      ['📅', 'calendar date day schedule deadline'],
      ['📆', 'tear off calendar date'],
      ['🗑️', 'wastebasket bin delete trash remove'],
      ['📇', 'card index contacts rolodex'],
      ['🗃️', 'card file box archive records'],
      ['🗄️', 'file cabinet archive storage records'],
      ['📋', 'clipboard checklist copy paste tasks'],
      ['📝', 'memo note write pencil draft edit'],
      ['✏️', 'pencil write edit draft'],
      ['🖊️', 'pen write sign ink'],
      ['🖋️', 'fountain pen sign signature ink'],
      ['🖌️', 'paintbrush design art'],
      ['📏', 'ruler measure straight'],
      ['📐', 'triangular ruler measure geometry'],
      ['✂️', 'scissors cut trim'],
      ['🔖', 'bookmark save mark label'],
      ['🏷️', 'label tag price category'],
      ['💼', 'briefcase business work job office'],
      ['📖', 'open book read manual reference'],
      ['📚', 'books library study reading'],
      ['🧾', 'receipt invoice bill expense'],
      ['💰', 'money bag cash funds budget rupee'],
      ['💵', 'banknote cash money dollar'],
      ['💴', 'yen banknote money currency'],
      ['💶', 'euro banknote money currency'],
      ['💷', 'pound banknote money currency'],
      ['💳', 'credit card payment pay debit'],
      ['🪙', 'coin money change currency'],
      ['🏦', 'bank building finance branch'],
      ['🏛️', 'classical building government institution court'],
      ['🏢', 'office building company work headquarters'],
      ['⚖️', 'balance scales justice law audit fair'],
      ['🔐', 'locked with key secure private access'],
      ['🔒', 'lock locked private secure closed'],
      ['🔓', 'unlock open unlocked access'],
      ['🔑', 'key access password unlock'],
      ['🗝️', 'old key access unlock secret'],
      ['✅', 'check tick done complete yes approved'],
      ['☑️', 'ballot check tick done selected'],
      ['✔️', 'check mark tick done yes'],
      ['❌', 'cross no wrong cancel fail remove'],
      ['❎', 'cross mark button no reject'],
      ['⭕', 'circle correct right o mark'],
      ['⏳', 'hourglass waiting time pending progress'],
      ['⌛', 'hourglass done time up finished'],
      ['⏰', 'alarm clock reminder deadline wake'],
      ['🕐', 'clock time hour schedule'],
      ['📞', 'telephone receiver call phone ring'],
      ['📱', 'mobile phone smartphone cell'],
      ['☎️', 'telephone landline call'],
      ['📠', 'fax machine send'],
      ['📧', 'email mail message send'],
      ['📨', 'incoming envelope mail received'],
      ['📩', 'envelope with arrow mail sent'],
      ['✉️', 'envelope mail letter email'],
      ['📮', 'postbox mail post send'],
      ['🔔', 'bell notification alert reminder ring'],
      ['🔕', 'bell with slash mute silence muted notifications'],
      ['📢', 'loudspeaker announce broadcast public'],
      ['📣', 'megaphone announce shout cheer'],
      ['🗣️', 'speaking head talk speech say'],
      ['💬', 'speech balloon comment message chat'],
      ['💭', 'thought balloon thinking idea'],
      ['🗨️', 'left speech bubble quote say'],
      ['🖥️', 'desktop computer monitor screen'],
      ['💻', 'laptop computer work macbook'],
      ['⌨️', 'keyboard type input'],
      ['🖨️', 'printer print paper'],
      ['🖱️', 'computer mouse click cursor'],
      ['💾', 'floppy disk save backup'],
      ['📀', 'dvd disc storage'],
      ['🗜️', 'clamp compress squeeze zip'],
      ['🔍', 'magnifying glass search find look zoom'],
      ['🔎', 'magnifying glass right search find inspect'],
      ['🔗', 'link url chain hyperlink'],
      ['📤', 'outbox tray sent upload send'],
      ['📥', 'inbox tray received download'],
      ['📦', 'package box parcel delivery shipment'],
      ['🎯', 'target bullseye goal aim objective'],
      ['🧮', 'abacus calculate count maths math accounts'],
      ['🪪', 'identification card id licence license pan'],
    ],
  },
  {
    id: 'objects',
    label: 'Objects',
    emoji: [
      ['💡', 'bulb idea light insight suggestion'],
      ['🔦', 'torch flashlight light search'],
      ['🕯️', 'candle light diya remembrance'],
      ['🪔', 'diya oil lamp diwali deepak festival'],
      ['🔥', 'fire hot lit burning urgent trending'],
      ['💥', 'collision boom explosion impact'],
      ['⚡', 'zap lightning fast power electric urgent'],
      ['✨', 'sparkles shiny new magic clean'],
      ['🌟', 'glowing star special standout'],
      ['⭐', 'star favourite favorite rating'],
      ['💫', 'dizzy star sparkle'],
      ['🎉', 'party popper celebrate congratulations launch hooray'],
      ['🎊', 'confetti ball celebrate party'],
      ['🎈', 'balloon party celebrate birthday'],
      ['🎁', 'gift present wrapped surprise'],
      ['🏆', 'trophy win award champion first'],
      ['🥇', 'gold medal first winner best'],
      ['🥈', 'silver medal second'],
      ['🥉', 'bronze medal third'],
      ['🏅', 'medal award achievement'],
      ['🎖️', 'military medal honour honor award'],
      ['👑', 'crown king queen best royal'],
      ['💎', 'gem diamond valuable precious premium'],
      ['🔧', 'wrench fix tool repair spanner'],
      ['🔨', 'hammer build fix tool'],
      ['🛠️', 'hammer and wrench tools build maintenance'],
      ['⚙️', 'gear settings config cog mechanism'],
      ['🧰', 'toolbox tools kit repair'],
      ['🔩', 'nut and bolt hardware fix'],
      ['🪛', 'screwdriver tool fix'],
      ['🧲', 'magnet attract pull'],
      ['🪜', 'ladder climb steps'],
      ['🧱', 'brick wall block build'],
      ['🚪', 'door entrance exit leave'],
      ['🪟', 'window view glass'],
      ['🛎️', 'bellhop bell service ring reception'],
      ['🧹', 'broom clean sweep tidy'],
      ['🧼', 'soap clean wash hygiene'],
      ['🧴', 'lotion bottle sanitiser sanitizer'],
      ['🪣', 'bucket pail water'],
      ['🔋', 'battery power charge energy'],
      ['🔌', 'plug power electric connect'],
      ['📡', 'satellite antenna signal broadcast network'],
      ['🛰️', 'satellite space orbit signal'],
      ['📷', 'camera photo picture snap'],
      ['📸', 'camera flash photo picture'],
      ['📹', 'video camera record film'],
      ['🎥', 'movie camera film shoot'],
      ['🎬', 'clapper board film action start'],
      ['🎧', 'headphones music listen audio'],
      ['🎤', 'microphone mic sing speak podcast'],
      ['🎵', 'musical note music song'],
      ['🎶', 'musical notes music song tune'],
      ['📻', 'radio broadcast news'],
      ['📺', 'television tv screen watch'],
      ['⏱️', 'stopwatch timer time race'],
      ['⏲️', 'timer clock countdown'],
      ['🧭', 'compass direction navigate north'],
      ['🗺️', 'world map travel navigate plan'],
      ['🧳', 'luggage suitcase travel trip pack'],
      ['☂️', 'umbrella rain monsoon cover'],
      ['🧧', 'red envelope gift money shagun'],
      ['🪄', 'magic wand magic fix spell'],
      ['🧿', 'nazar amulet evil eye protection'],
      ['🪷', 'lotus flower india peace'],
      ['🕉️', 'om hindu spiritual aum'],
      ['💊', 'pill medicine health tablet'],
      ['🩺', 'stethoscope doctor health checkup diagnosis'],
      ['🧪', 'test tube experiment lab science'],
      ['🔬', 'microscope research science examine detail'],
      ['🧬', 'dna genetics science biology'],
      ['⚗️', 'alembic chemistry experiment distil'],
    ],
  },
  {
    id: 'symbols',
    label: 'Symbols',
    emoji: [
      ['❤️', 'red heart love like'],
      ['🧡', 'orange heart love'],
      ['💛', 'yellow heart love friendship'],
      ['💚', 'green heart love'],
      ['💙', 'blue heart love'],
      ['💜', 'purple heart love'],
      ['🖤', 'black heart love dark'],
      ['🤍', 'white heart love pure'],
      ['🤎', 'brown heart love'],
      ['💔', 'broken heart sad hurt'],
      ['❣️', 'heart exclamation love emphasis'],
      ['💕', 'two hearts love affection'],
      ['💖', 'sparkling heart love special'],
      ['💗', 'growing heart love'],
      ['💘', 'heart with arrow love cupid'],
      ['💝', 'heart with ribbon gift love'],
      ['💯', 'hundred perfect score agree full marks'],
      ['‼️', 'double exclamation important urgent'],
      ['⁉️', 'exclamation question surprised confused'],
      ['❗', 'exclamation important warning attention'],
      ['❓', 'question help unsure ask'],
      ['❔', 'white question mark ask unsure'],
      ['⚠️', 'warning caution alert danger careful'],
      ['🚫', 'prohibited forbidden no not allowed blocked'],
      ['⛔', 'no entry stop forbidden blocked'],
      ['🔴', 'red circle stop blocked critical'],
      ['🟠', 'orange circle warning at risk'],
      ['🟡', 'yellow circle caution pending'],
      ['🟢', 'green circle go done healthy ok'],
      ['🔵', 'blue circle info neutral'],
      ['🟣', 'purple circle'],
      ['⚫', 'black circle off'],
      ['⚪', 'white circle empty'],
      ['🟥', 'red square block critical'],
      ['🟩', 'green square block done'],
      ['🟨', 'yellow square block pending'],
      ['🔺', 'red triangle up increase'],
      ['🔻', 'red triangle down decrease'],
      ['▶️', 'play start run resume'],
      ['⏸️', 'pause hold wait'],
      ['⏹️', 'stop end halt'],
      ['⏭️', 'next skip forward'],
      ['🔁', 'repeat loop again recurring'],
      ['🔄', 'refresh sync reload update again'],
      ['↩️', 'return back undo reply'],
      ['➡️', 'right arrow next forward then'],
      ['⬅️', 'left arrow back previous'],
      ['⬆️', 'up arrow increase above'],
      ['⬇️', 'down arrow decrease below'],
      ['🔼', 'up button increase'],
      ['🔽', 'down button decrease'],
      ['➕', 'plus add more increase'],
      ['➖', 'minus subtract less remove'],
      ['✖️', 'multiply times cross'],
      ['➗', 'divide division'],
      ['🟰', 'equals equal same'],
      ['♻️', 'recycle reuse sustainable green'],
      ['🆕', 'new fresh badge'],
      ['🆗', 'ok fine approved'],
      ['🆙', 'up upgrade level'],
      ['🔝', 'top best priority'],
      ['🔜', 'soon coming shortly'],
      ['🈵', 'no vacancy full'],
      ['🅿️', 'parking park'],
      ['🚻', 'restroom toilet washroom'],
      ['©️', 'copyright legal rights'],
      ['®️', 'registered trademark legal'],
      ['™️', 'trademark brand legal'],
      ['#️⃣', 'hash channel number tag'],
      ['*️⃣', 'asterisk star footnote'],
      ['0️⃣', 'zero number 0'],
      ['1️⃣', 'one number 1 first'],
      ['2️⃣', 'two number 2 second'],
      ['3️⃣', 'three number 3 third'],
      ['4️⃣', 'four number 4'],
      ['5️⃣', 'five number 5'],
      ['6️⃣', 'six number 6'],
      ['7️⃣', 'seven number 7'],
      ['8️⃣', 'eight number 8'],
      ['9️⃣', 'nine number 9'],
      ['🔟', 'ten number 10'],
    ],
  },
  {
    id: 'nature',
    label: 'Animals & nature',
    emoji: [
      ['🐶', 'dog puppy pet'],
      ['🐱', 'cat kitten pet'],
      ['🐭', 'mouse rodent'],
      ['🐹', 'hamster pet'],
      ['🐰', 'rabbit bunny'],
      ['🦊', 'fox clever'],
      ['🐻', 'bear'],
      ['🐼', 'panda'],
      ['🐨', 'koala'],
      ['🐯', 'tiger'],
      ['🦁', 'lion brave king'],
      ['🐮', 'cow cattle'],
      ['🐷', 'pig'],
      ['🐸', 'frog'],
      ['🐵', 'monkey'],
      ['🐔', 'chicken hen'],
      ['🐧', 'penguin'],
      ['🐦', 'bird tweet'],
      ['🦅', 'eagle bird sharp'],
      ['🦉', 'owl night wise'],
      ['🦋', 'butterfly transform'],
      ['🐝', 'bee busy honey'],
      ['🐞', 'ladybug ladybird luck'],
      ['🐜', 'ant work small'],
      ['🕷️', 'spider web'],
      ['🐢', 'turtle slow tortoise'],
      ['🐍', 'snake'],
      ['🦎', 'lizard'],
      ['🐙', 'octopus'],
      ['🐠', 'fish tropical'],
      ['🐬', 'dolphin'],
      ['🐳', 'whale'],
      ['🦈', 'shark'],
      ['🐘', 'elephant ganesh big'],
      ['🐪', 'camel desert'],
      ['🐄', 'cow cattle dairy'],
      ['🐎', 'horse race'],
      ['🦚', 'peacock india national bird'],
      ['🦜', 'parrot bird talk'],
      ['🌱', 'seedling growth new sprout'],
      ['🌿', 'herb leaf green plant'],
      ['🍀', 'four leaf clover luck lucky'],
      ['🌳', 'tree nature green'],
      ['🌲', 'evergreen tree forest'],
      ['🌴', 'palm tree beach tropical holiday'],
      ['🌵', 'cactus desert dry'],
      ['🌸', 'cherry blossom flower spring'],
      ['🌼', 'blossom flower daisy'],
      ['🌻', 'sunflower flower sun'],
      ['🌹', 'rose flower love'],
      ['🌺', 'hibiscus flower tropical'],
      ['💐', 'bouquet flowers congratulations thanks'],
      ['🍁', 'maple leaf autumn fall'],
      ['🍂', 'fallen leaves autumn fall'],
      ['🌾', 'sheaf of rice crop harvest agriculture'],
      ['🌞', 'sun face sunny bright day'],
      ['☀️', 'sun sunny clear weather'],
      ['🌤️', 'sun behind cloud partly cloudy'],
      ['☁️', 'cloud cloudy overcast'],
      ['🌧️', 'rain cloud raining monsoon wet'],
      ['⛈️', 'thunderstorm storm lightning rain'],
      ['🌈', 'rainbow colour color hope pride'],
      ['❄️', 'snowflake cold winter freeze'],
      ['⛄', 'snowman winter cold'],
      ['🌊', 'wave water sea ocean flood'],
      ['🌍', 'earth globe europe africa world'],
      ['🌏', 'earth globe asia australia world india'],
      ['🌙', 'crescent moon night'],
      ['🌚', 'new moon face dark cheeky'],
      ['🌝', 'full moon face bright'],
      ['💧', 'droplet water drop'],
      ['🔥', 'fire flame hot burning'],
    ],
  },
  {
    id: 'food',
    label: 'Food & drink',
    emoji: [
      ['☕', 'coffee tea chai break hot drink'],
      ['🍵', 'tea green tea chai cup'],
      ['🫖', 'teapot chai tea brew'],
      ['🧋', 'bubble tea boba drink'],
      ['🥤', 'cup with straw soft drink cold'],
      ['🧃', 'juice box drink'],
      ['🍺', 'beer pint drink pub'],
      ['🍻', 'clinking beer mugs cheers celebrate'],
      ['🥂', 'clinking glasses cheers celebrate toast'],
      ['🍷', 'wine glass drink'],
      ['🥃', 'tumbler whisky whiskey drink'],
      ['🍸', 'cocktail drink martini'],
      ['🍾', 'bottle with popping cork champagne celebrate'],
      ['🥛', 'glass of milk dairy'],
      ['🍼', 'baby bottle milk'],
      ['🍽️', 'fork knife plate meal dinner eat'],
      ['🍴', 'fork and knife eat food'],
      ['🥄', 'spoon eat'],
      ['🍚', 'cooked rice bowl meal'],
      ['🍛', 'curry rice indian meal thali'],
      ['🍲', 'pot of food stew soup dal'],
      ['🥘', 'shallow pan of food paella biryani'],
      ['🫓', 'flatbread roti naan chapati paratha'],
      ['🍞', 'bread loaf toast'],
      ['🥖', 'baguette bread french'],
      ['🥐', 'croissant pastry breakfast'],
      ['🧀', 'cheese dairy'],
      ['🥗', 'green salad healthy vegetables'],
      ['🥙', 'stuffed flatbread kathi roll wrap shawarma'],
      ['🌯', 'burrito wrap roll'],
      ['🌮', 'taco mexican'],
      ['🍕', 'pizza slice italian'],
      ['🍔', 'hamburger burger fast food'],
      ['🍟', 'french fries chips fast food'],
      ['🌭', 'hot dog fast food'],
      ['🥪', 'sandwich lunch'],
      ['🍜', 'steaming bowl noodles ramen soup'],
      ['🍣', 'sushi japanese'],
      ['🥟', 'dumpling momo gyoza'],
      ['🍳', 'cooking fried egg breakfast'],
      ['🥚', 'egg'],
      ['🍿', 'popcorn film movie snack'],
      ['🧂', 'salt seasoning'],
      ['🍰', 'shortcake cake dessert birthday'],
      ['🎂', 'birthday cake celebrate anniversary'],
      ['🧁', 'cupcake dessert sweet'],
      ['🍩', 'doughnut donut sweet'],
      ['🍪', 'cookie biscuit sweet'],
      ['🍫', 'chocolate bar sweet'],
      ['🍬', 'candy sweet toffee'],
      ['🍦', 'ice cream soft serve dessert'],
      ['🍯', 'honey pot sweet'],
      ['🍎', 'red apple fruit'],
      ['🍌', 'banana fruit'],
      ['🍊', 'tangerine orange fruit citrus'],
      ['🍋', 'lemon citrus sour nimbu'],
      ['🍉', 'watermelon fruit summer'],
      ['🍇', 'grapes fruit'],
      ['🥭', 'mango fruit aam summer'],
      ['🍍', 'pineapple fruit'],
      ['🥥', 'coconut nariyal'],
      ['🍓', 'strawberry fruit berry'],
      ['🥑', 'avocado healthy'],
      ['🍅', 'tomato vegetable'],
      ['🥕', 'carrot vegetable'],
      ['🌽', 'corn maize bhutta'],
      ['🌶️', 'hot pepper chilli chili spicy mirchi'],
      ['🧅', 'onion pyaaz vegetable'],
      ['🥔', 'potato aloo vegetable'],
      ['🫘', 'beans dal pulses rajma'],
      ['🥜', 'peanuts nuts'],
    ],
  },
  {
    id: 'travel',
    label: 'Travel & places',
    emoji: [
      ['🚗', 'car drive automobile'],
      ['🚕', 'taxi cab ride'],
      ['🚙', 'suv car'],
      ['🚌', 'bus transport'],
      ['🚎', 'trolleybus transport'],
      ['🏎️', 'racing car fast speed'],
      ['🚓', 'police car'],
      ['🚑', 'ambulance emergency'],
      ['🚒', 'fire engine emergency'],
      ['🛺', 'auto rickshaw tuk tuk india'],
      ['🚲', 'bicycle cycle bike'],
      ['🛵', 'motor scooter scooty ride'],
      ['🏍️', 'motorcycle bike ride'],
      ['🚚', 'delivery truck lorry shipment'],
      ['🚛', 'articulated lorry truck freight'],
      ['🚜', 'tractor farm agriculture'],
      ['🚂', 'locomotive train rail'],
      ['🚆', 'train rail commute'],
      ['🚇', 'metro subway underground'],
      ['✈️', 'aeroplane airplane flight travel fly'],
      ['🛫', 'aeroplane departure takeoff leaving'],
      ['🛬', 'aeroplane arrival landing arrived'],
      ['🚁', 'helicopter fly'],
      ['🚀', 'rocket launch fast ship shipped'],
      ['🛸', 'flying saucer ufo'],
      ['⛵', 'sailboat sail sea'],
      ['🚢', 'ship sea cargo freight'],
      ['⚓', 'anchor sea stable'],
      ['🏠', 'house home'],
      ['🏡', 'house with garden home'],
      ['🏘️', 'houses neighbourhood neighborhood residential'],
      ['🏗️', 'building construction wip work in progress'],
      ['🏭', 'factory manufacturing industry plant'],
      ['🏬', 'department store shop retail'],
      ['🏨', 'hotel stay accommodation'],
      ['🏥', 'hospital health medical'],
      ['🏫', 'school education college'],
      ['⛪', 'church religion'],
      ['🕌', 'mosque religion'],
      ['🛕', 'hindu temple mandir religion'],
      ['🕍', 'synagogue religion'],
      ['🗿', 'moai statue stone face'],
      ['🗼', 'tower landmark'],
      ['🌃', 'night with stars city night'],
      ['🌆', 'cityscape dusk evening city'],
      ['🌉', 'bridge at night'],
      ['🏝️', 'desert island holiday beach leave'],
      ['🏔️', 'snow capped mountain himalaya peak'],
      ['⛰️', 'mountain hill peak climb'],
      ['🏕️', 'camping tent outdoors'],
      ['🏖️', 'beach with umbrella holiday leave vacation'],
    ],
  },
  {
    id: 'activity',
    label: 'Activities',
    emoji: [
      ['⚽', 'football soccer ball sport'],
      ['🏀', 'basketball sport'],
      ['🏈', 'american football sport'],
      ['⚾', 'baseball sport'],
      ['🏏', 'cricket bat ball india sport match'],
      ['🎾', 'tennis sport'],
      ['🏐', 'volleyball sport'],
      ['🏉', 'rugby sport'],
      ['🎱', 'pool 8 ball billiards'],
      ['🏓', 'ping pong table tennis'],
      ['🏸', 'badminton shuttlecock sport'],
      ['🥅', 'goal net score'],
      ['⛳', 'golf flag hole'],
      ['🏹', 'bow and arrow archery target aim'],
      ['🎣', 'fishing pole catch'],
      ['🥊', 'boxing glove fight'],
      ['🥋', 'martial arts uniform karate judo'],
      ['⛸️', 'ice skate skating'],
      ['🎿', 'skis skiing snow'],
      ['🏂', 'snowboarder snow sport'],
      ['🏋️', 'weight lifting gym workout strong'],
      ['🚴', 'cycling bike ride'],
      ['🏊', 'swimming swim pool'],
      ['🤸', 'cartwheel gymnastics flexible'],
      ['🎮', 'video game controller gaming play'],
      ['🕹️', 'joystick game arcade'],
      ['🎲', 'game die dice chance random'],
      ['♟️', 'chess pawn strategy'],
      ['🧩', 'puzzle piece fit solve problem'],
      ['🎨', 'artist palette art design paint creative'],
      ['🎭', 'performing arts theatre theater drama'],
      ['🎪', 'circus tent show'],
      ['🎟️', 'admission ticket entry event'],
      ['🎫', 'ticket entry event pass'],
      ['🪁', 'kite patang uttarayan makar sankranti'],
      ['🧗', 'climbing climb effort challenge'],
      ['🏇', 'horse racing race'],
      ['🎯', 'direct hit bullseye target goal'],
    ],
  },
];

/**
 * Every entry, flattened, with its category id — the shape search wants.
 *
 * Built once at module evaluation, which happens inside the lazy chunk, so it
 * costs nothing until the picker is opened for the first time in a session.
 */
export const ALL = CATEGORIES.flatMap(c =>
  c.emoji.map(([char, keywords]) => ({ char, keywords, cat: c.id }))
);

/**
 * Substring over the keyword string, in declaration order, capped.
 *
 * NOT fuzzy and not scored, per proposal 09. A substring test means "thu" finds
 * 👍 (thumbs) and 🌩 (thunderstorm) and nothing else, which is a rule a reader
 * can hold in their head; a fuzzy matcher would also return 😴 for "sad" and the
 * only way to find anything after that is to scroll.
 *
 * The cap is the one concession to the grid: past ~120 hits the results stop
 * being a list and start being the whole dataset in a different order, and a
 * query that vague is better narrowed than paged.
 */
export function searchEmoji(query, limit = 120) {
  const q = String(query || '').trim().toLowerCase();
  if (!q) return [];
  const out = [];
  for (const e of ALL) {
    if (e.keywords.includes(q)) {
      out.push(e);
      if (out.length >= limit) break;
    }
  }
  return out;
}
