-- 201 · WHO LAST CHANGED THIS ROW — `updated_by` on the 55 record tables.
--
-- THERE IS ONLY ONE `staging` SCHEMA AND PRODUCTION WRITES TO IT TOO. Applying
-- this file is a production change, exactly as 093-097 and 200 say. Apply it by
-- hand; nothing here is applied automatically and no application code applies
-- it.
--
-- ═══════════════════════════════════════════════════════════════════════════
-- WHY — workstream E, measured against the live catalogue on 2026-08-23
-- ═══════════════════════════════════════════════════════════════════════════
--
-- The owner wants created-by, last-updated-by and both dates on every table in
-- the product. `frontend/src/components/ui/CreatedColumn.jsx` shipped the
-- rendering half: `CreatedCell`, `UpdatedCell` and `ByCell` — the last of which
-- renders a RESOLVED NAME and distinguishes "nobody did this" (an em dash) from
-- "the account that did it is gone" (`unknown`). Its own commit message names
-- the blocker it could not fix from the frontend, and this file is that
-- blocker.
--
-- Read off `information_schema` on 2026-08-23, over the 265 base tables in
-- `staging`:
--
--     created_at   206 tables (78%)
--     created_by    74 tables (28%)   -- 66 TEXT, 8 uuid; see 202
--     updated_at    97 tables (37%)
--     updated_by     3 tables ( 1%)   -- hub_connector_credentials,
--                                     -- org_billing_lines, pahchan_policy_overrides
--
-- Three. So `UpdatedHead` and `ByHead` over `updated_by` would today be headers
-- above an em dash on every row of every table in the product. A column nothing
-- can fill is worse than no column at all, because an empty audit trail looks
-- exactly like an audit trail that looked and found nothing.
--
-- ═══════════════════════════════════════════════════════════════════════════
-- WHAT — 55 tables, and the 210 that are DELIBERATELY NOT HERE
-- ═══════════════════════════════════════════════════════════════════════════
--
-- This is NOT a sweep. A blanket `updated_by` across 265 tables would land
-- ~200 columns that nothing could ever write, on tables where the question does
-- not arise. The list was cut on one test: IS THERE A PERSON WHO COULD AMEND
-- THIS ROW, AND IS THAT A DIFFERENT FACT FROM WHO CREATED IT?
--
-- Section 1 (40 tables) already stamps `updated_at`, so each gains one column.
-- Section 2 (15 tables) stamps neither, so each gains `updated_at`,
-- `updated_by` and a `touch_updated_at` trigger.
--
-- EXCLUDED, with the reason — the exclusions ARE the argument:
--
--   · APPEND-ONLY LEDGERS AND EVENT LOGS. The row IS the event and is never
--     amended; a correction is a NEW row, which is the entire point of the
--     shape. `hub_credit_transactions` and `hub_org_credit_transactions` (095
--     states it: a spend is reversed by a reversing row, and
--     `tests/test_credits_isolation.py` fails the build if any file other than
--     `services/credits.py` so much as names them); `vikray_stock_moves`
--     (`quantity_delta` + `reason` — a wrong move is undone by a counter-move);
--     `graha_activities` (a call HAPPENED); `prachar_events`;
--     `client_engagement_predecessor_comms` (`dispatched_on`, `proof_ref` — the
--     row is a letter that left the building); `outbound_log` (098 forbids a
--     second writer outright); `audit_log`; `sign_audit_log`; `niyam_events`;
--     `graha_contact_merges`.
--
--   · MACHINE-WRITTEN ROWS with no human author at any point. `reminders`
--     (2,561 rows, generated by the reminder scan; its only state change is
--     delivery, already recorded truthfully by `status` + `sent_at` — no person
--     edits a reminder); `hub_publish_queue` (`status`/`retry_count`/
--     `published_at`, advanced by cron-publish); `vetana_payslips` (1,112 rows
--     GENERATED BY a payroll run — the run carries the author, the payslip is
--     its output); `hr_attendance`; `pahchan_punches`;
--     `analytics_metrics_daily`; `pulse_*`; `usage_tracking`; `niyam_runs`;
--     `hub_skill_runs`; `hub_scraper_runs`.
--
--   · JOIN, COUNTER AND PREFERENCE TABLES, where a row is a fact about a pair
--     and not a record anybody authored. `user_roles`;
--     `samvada_channel_members`; `org_member_modules`; `graha_contact_labels`;
--     `module_subscriptions`; `vikray_stock` (a counter); `user_column_prefs`
--     and `user_tab_prefs` (the owner is the only possible author and is
--     already the key).
--
--   · CHILD ROWS OF A PARENT DOCUMENT. `ganit_po_lines`,
--     `invoice_billing_lines`, `prachar_sequence_steps`, `niyam_rule_steps`,
--     `sign_fields`, `ganit_bank_statement_lines`. Editing a line is editing
--     the document; the trail belongs on the document, where one entry is worth
--     more than fifteen scattered across its lines.
--
--   · WHERE `updated_by` COULD ONLY EVER REPEAT `created_by`.
--     `hub_chat_sessions` belongs to exactly one person, who is the only one
--     who can touch it. A column provably always equal to its neighbour is not
--     an audit trail, it is a duplicate.
--
--   · DEAD LEGACY. `crm_accounts`, `crm_activities`, `crm_contacts`,
--     `crm_invoices`, `crm_leads`, `crm_quotations` — six tables carrying a
--     `uuid` `created_by`, ZERO rows apiece, and no writer anywhere in the
--     backend; the only files naming any of them are a skill's own comments
--     saying they are empty. `graha_automations` is the seventh: 0 rows, 0
--     writers. The live CRM is `graha_*`. Likewise `hr_*` and `pay_*`,
--     superseded in place by `manav_*` and `vetana_*`, and every `*_backup_*`.
--
--   · `manav_expense_claims` — no creator column and no `updated_at`, but its
--     only state change is approval, and `approved_by` + `approved_at` already
--     record it truthfully. The claimant is `employee_id`. Nothing is missing.
--
-- ═══════════════════════════════════════════════════════════════════════════
-- TEXT, NOT UUID — and this repo has already paid for it three times
-- ═══════════════════════════════════════════════════════════════════════════
--
-- `public.users.user_id` is TEXT (`user_549c9cac35aa`), confirmed against the
-- live catalogue rather than assumed. Every column in this file is TEXT. The
-- scars: `030_created_by_uuid_to_text.sql` ("500 errors on every INSERT"),
-- `092_sales_target_salesperson_is_a_user_id.sql` (a sales target nobody could
-- ever save, reaching the browser as a CORS error), and `097`, which put the
-- rule into the migrations README. `202` in this same workstream is the fourth:
-- `graha_web_forms.created_by` is `uuid` to this day and is 500ing to this day.
--
-- NO FOREIGN KEY to `public.users`, matching all three existing `updated_by`
-- columns and every `created_by` on these tables. An account can be removed and
-- the trail must survive it as an id that no longer resolves — `ByCell` renders
-- exactly that case as `unknown`, deliberately distinct from the em dash it
-- renders for NULL. An FK would force the choice between deleting the trail and
-- refusing to delete the account.
--
-- NO INDEX. Nothing queries a record BY the person who last touched it; the
-- column is read on the row you already have. Fifty-five indexes maintained on
-- every UPDATE to answer a question nobody asks is a cost with no buyer.
--
-- NO CHECK CONSTRAINT, for two reasons. The three existing `updated_by` columns
-- carry none, and a rule enforced on 55 of 58 identical columns looks enforced
-- and is not. And — THE TRAP THIS PROJECT HAS ALREADY SPRUNG — an inline CHECK
-- on `ADD COLUMN IF NOT EXISTS` is skipped ENTIRELY when the column already
-- exists, so a re-run would silently leave a table holding the column and not
-- the constraint. Read `pg_constraint`, never a migration file, to learn
-- whether a constraint is really there.
--
-- ═══════════════════════════════════════════════════════════════════════════
-- NO BACKFILL. NONE. THAT IS THE POINT.
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Who amended a row before today was never recorded anywhere, so there is
-- nothing to backfill FROM. Copying `created_by` into `updated_by` would be the
-- worst outcome available: it would name one specific colleague as the author
-- of every change ever made to a row — including the changes somebody else
-- made — and it would read as a fact rather than as a guess. A NULL is visibly
-- unknown; a wrong name is not. 097 argued this for one column; it holds for
-- fifty-five.
--
-- The NULLs stay readable against columns that already exist:
--
--     updated_at IS NULL                          never modified
--     updated_at > created_at, updated_by NULL    modified before this file, or
--                                                 by a cron or trigger since
--     updated_by IS NOT NULL                      a person, and we know which
--
-- ═══════════════════════════════════════════════════════════════════════════
-- RISK
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Additive only: 70 `ADD COLUMN IF NOT EXISTS`, every one nullable with NO
-- DEFAULT, so every one is a catalog update with NO TABLE REWRITE (PG 11+). No
-- DROP, no `ALTER … TYPE`, no `SET NOT NULL`, no UPDATE of any row, no data
-- read and none written. Replayable: a second run is a no-op end to end.
--
-- WRITE-PATH SIDE EFFECTS: none on existing rows, and none observable by any
-- request in flight. Nothing on `staging` or on `main` names `updated_by` on
-- any of these tables until the routers land, and a `SELECT *` merely gains one
-- NULL column — every router in this codebase reads its rows by name.
--
-- Section 2's `updated_at` is NULLABLE WITH NO DEFAULT, deliberately unlike
-- `138_delta_sync.sql`, which used `NOT NULL DEFAULT NOW()`. 138 needed that
-- because delta sync filters `updated_at > since` and cannot carry a NULL.
-- Here a default would stamp this migration's own timestamp onto ~1,300
-- historical rows and assert that every one of them was modified today — the
-- same lie as backfilling `updated_by`, in the neighbouring column. None of
-- these 15 tables has a `?since=` endpoint; none could have, having had no
-- `updated_at` until this file.
--
-- THE 15 NEW TRIGGERS are the only behavioural change here. Each is `BEFORE
-- UPDATE … FOR EACH ROW` calling `staging.touch_updated_at()`, which already
-- exists (138) and performs one assignment. They exist so that `updated_at` is
-- true whoever wrote the row, including a cron that never heard of the column;
-- the alternative is a column that stays NULL wherever a writer forgot, which
-- is the exact failure this workstream exists to end. `updated_by` gets NO
-- trigger and CANNOT have one: a trigger does not know who is holding the
-- connection. It is set by the write path, in the same UPDATE.
--
-- LOCKS: each `ALTER TABLE` takes ACCESS EXCLUSIVE on its own table for a
-- catalog update — microseconds of work, but it queues behind any open
-- transaction on that table and blocks every reader arriving after it. 55
-- tables in ONE transaction means all 55 locks are held until COMMIT.
-- `lock_timeout` turns the bad case into a clean rollback of the whole file
-- instead of a stall spread across the product. Run it when traffic is low.
--
-- APPLYING THIS FILE RECORDS NOTHING BY ITSELF. Every column stays NULL until
-- the routers set it, which is the backend half of workstream E.

BEGIN;

SET LOCAL lock_timeout = '5s';

-- ── 1. `updated_by` on the 40 tables that already stamp `updated_at` ────

ALTER TABLE staging.analytics_alerts
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.analytics_views
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.client_engagements
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.client_obligations
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.dristi_dashboards
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.dsc_register
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.ganit_bank_formats
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.ganit_contracts
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.ganit_expenses
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.ganit_invoices
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.ganit_purchase_orders
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.ganit_tds_challans
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.graha_clients
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.graha_contacts
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.graha_deals
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.graha_documents
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.graha_follow_ups
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.hub_content_items
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.hub_kb_documents
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.manav_announcements
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.manav_assets
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.manav_commission_bands
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.manav_commission_schemes
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.manav_employees
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.mkt_campaigns
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.mkt_landing_pages
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.mkt_segments
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.niyam_rules
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.notice_register
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.prachar_automations
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.prachar_campaigns
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.prachar_sequences
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.prachar_templates
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.sales_playbooks
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.sales_proposals
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.samvada_channels
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.sign_documents
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.udin_register
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.vetana_salary_structures
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
ALTER TABLE staging.vikray_orders
    ADD COLUMN IF NOT EXISTS updated_by TEXT;

-- ── 2. `updated_at` + `updated_by` on the 15 that stamp neither ─────────

ALTER TABLE staging.dristi_scheduled_reports
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_dristi_scheduled_reports ON staging.dristi_scheduled_reports;
CREATE TRIGGER trg_touch_dristi_scheduled_reports
    BEFORE UPDATE ON staging.dristi_scheduled_reports
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.ganit_recurring
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_ganit_recurring ON staging.ganit_recurring;
CREATE TRIGGER trg_touch_ganit_recurring
    BEFORE UPDATE ON staging.ganit_recurring
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.ganit_vendor_bills
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_ganit_vendor_bills ON staging.ganit_vendor_bills;
CREATE TRIGGER trg_touch_ganit_vendor_bills
    BEFORE UPDATE ON staging.ganit_vendor_bills
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.ganit_vendor_payments
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_ganit_vendor_payments ON staging.ganit_vendor_payments;
CREATE TRIGGER trg_touch_ganit_vendor_payments
    BEFORE UPDATE ON staging.ganit_vendor_payments
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.graha_web_forms
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_graha_web_forms ON staging.graha_web_forms;
CREATE TRIGGER trg_touch_graha_web_forms
    BEFORE UPDATE ON staging.graha_web_forms
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.manav_job_openings
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_manav_job_openings ON staging.manav_job_openings;
CREATE TRIGGER trg_touch_manav_job_openings
    BEFORE UPDATE ON staging.manav_job_openings
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.manav_schedules
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_manav_schedules ON staging.manav_schedules;
CREATE TRIGGER trg_touch_manav_schedules
    BEFORE UPDATE ON staging.manav_schedules
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.manav_shift_bids
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_manav_shift_bids ON staging.manav_shift_bids;
CREATE TRIGGER trg_touch_manav_shift_bids
    BEFORE UPDATE ON staging.manav_shift_bids
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.mkt_email_templates
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_mkt_email_templates ON staging.mkt_email_templates;
CREATE TRIGGER trg_touch_mkt_email_templates
    BEFORE UPDATE ON staging.mkt_email_templates
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.mkt_web_forms
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_mkt_web_forms ON staging.mkt_web_forms;
CREATE TRIGGER trg_touch_mkt_web_forms
    BEFORE UPDATE ON staging.mkt_web_forms
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.sales_proposal_templates
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_sales_proposal_templates ON staging.sales_proposal_templates;
CREATE TRIGGER trg_touch_sales_proposal_templates
    BEFORE UPDATE ON staging.sales_proposal_templates
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.sales_targets
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_sales_targets ON staging.sales_targets;
CREATE TRIGGER trg_touch_sales_targets
    BEFORE UPDATE ON staging.sales_targets
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.vetana_loans
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_vetana_loans ON staging.vetana_loans;
CREATE TRIGGER trg_touch_vetana_loans
    BEFORE UPDATE ON staging.vetana_loans
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.vetana_payroll_runs
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_vetana_payroll_runs ON staging.vetana_payroll_runs;
CREATE TRIGGER trg_touch_vetana_payroll_runs
    BEFORE UPDATE ON staging.vetana_payroll_runs
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

ALTER TABLE staging.vikray_targets
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS updated_by TEXT;
DROP TRIGGER IF EXISTS trg_touch_vikray_targets ON staging.vikray_targets;
CREATE TRIGGER trg_touch_vikray_targets
    BEFORE UPDATE ON staging.vikray_targets
    FOR EACH ROW EXECUTE FUNCTION staging.touch_updated_at();

-- ── 3. The comment, on every one of the 55 ──────────────────────────────

COMMENT ON COLUMN staging.analytics_alerts.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.analytics_views.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.client_engagements.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.client_obligations.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.dristi_dashboards.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.dsc_register.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.ganit_bank_formats.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.ganit_contracts.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.ganit_expenses.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.ganit_invoices.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.ganit_purchase_orders.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.ganit_tds_challans.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.graha_clients.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.graha_contacts.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.graha_deals.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.graha_documents.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.graha_follow_ups.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.hub_content_items.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.hub_kb_documents.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.manav_announcements.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.manav_assets.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.manav_commission_bands.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.manav_commission_schemes.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.manav_employees.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.mkt_campaigns.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.mkt_landing_pages.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.mkt_segments.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.niyam_rules.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.notice_register.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.prachar_automations.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.prachar_campaigns.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.prachar_sequences.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.prachar_templates.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.sales_playbooks.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.sales_proposals.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.samvada_channels.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.sign_documents.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.udin_register.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.vetana_salary_structures.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.vikray_orders.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.dristi_scheduled_reports.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.ganit_recurring.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.ganit_vendor_bills.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.ganit_vendor_payments.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.graha_web_forms.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.manav_job_openings.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.manav_schedules.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.manav_shift_bids.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.mkt_email_templates.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.mkt_web_forms.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.sales_proposal_templates.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.sales_targets.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.vetana_loans.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.vetana_payroll_runs.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';
COMMENT ON COLUMN staging.vikray_targets.updated_by IS
    'public.users.user_id (TEXT) of the LAST person to amend this row. NULL = never amended by a person since this column existed. Set by the write path in the same UPDATE that changes the row; no trigger can know an actor.';

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════════
-- VERIFY — read the catalogue, never this file
-- ═══════════════════════════════════════════════════════════════════════════
--
--   -- 58 = the 3 that already had it, plus the 55 here.
--   SELECT count(*) FROM information_schema.columns
--    WHERE table_schema='staging' AND column_name='updated_by';
--
--   -- every one of them TEXT. Expect ZERO rows.
--   SELECT table_name, data_type FROM information_schema.columns
--    WHERE table_schema='staging' AND column_name='updated_by'
--      AND data_type <> 'text';
--
--   -- the 15 new triggers, read from pg_trigger and not from section 2.
--   SELECT c.relname, t.tgname FROM pg_trigger t
--     JOIN pg_class c ON c.oid = t.tgrelid
--     JOIN pg_namespace n ON n.oid = c.relnamespace
--    WHERE n.nspname='staging' AND NOT t.tgisinternal
--      AND t.tgname LIKE 'trg_touch_%' ORDER BY 1;
--
--   -- NOTHING was backfilled. Every one of these must be 0.
--   SELECT count(updated_by) FROM staging.ganit_invoices;    -- 0 of 785
--   SELECT count(updated_by) FROM staging.graha_clients;     -- 0 of  91
--   SELECT count(updated_at) FROM staging.manav_schedules;   -- 0 of 867
--
-- ═══════════════════════════════════════════════════════════════════════════
-- ROLLBACK
-- ═══════════════════════════════════════════════════════════════════════════
--
-- Safe and total while the routers still do not write these columns. AFTER they
-- do, dropping them DESTROYS the recorded trail and there is no second copy of
-- it anywhere.
--
--   BEGIN;
--   -- for each table in section 2:
--   --   DROP TRIGGER IF EXISTS trg_touch_<t> ON staging.<t>;
--   --   ALTER TABLE staging.<t> DROP COLUMN IF EXISTS updated_at;
--   -- for every table in sections 1 and 2:
--   --   ALTER TABLE staging.<t> DROP COLUMN IF EXISTS updated_by;
--   COMMIT;
--
-- `staging.touch_updated_at()` is SHARED — 138, 139 and 160 attach it to eight
-- other tables. Drop the triggers if you must; never drop the function.
