// Ganit · products & services — the catalogue invoice lines are filled from.
import React, { useCallback, useEffect, useState } from 'react';
import { api, rows } from '../../lib/api';
import { useToast } from '../../components/ui/toast';
import { EmptyState } from '../../components/ui/EmptyState';
import ErrorState, { errorKind } from '../../components/ui/ErrorState';
import { SkeletonRegion, SkeletonTable } from '../../components/ui/Skeleton';
import ConfirmDialog from '../../components/ui/ConfirmDialog';
import { Badge } from './_shared';
import { inr } from '../../lib/inr';
import useModuleWrite from '../../hooks/useModuleWrite';
import useTableView from '../../hooks/useTableView';
import TableToolbar from '../../components/ui/TableToolbar';
import { HeadCell } from '../../components/ui/Table';
import { CreatedHead, CreatedCell } from '../../components/ui/CreatedColumn';

const BLANK = { name: '', hsn_code: '', sac_code: '', unit: 'NOS', price: '', cost_price: '', gst_rate: 18, description: '', is_service: false };

/* Cost is optional, and an EMPTY cost is null rather than zero. Zero says "this
   costs us nothing", which would render every product as pure profit; null says
   "not recorded", and the margin column shows a dash. A figure that is unknown
   must look unknown. `margin` and `margin_pct` are generated by the database
   (migration 137), so nothing here computes them — a margin computed in the UI
   is a fourth place for the number to disagree with itself. */
const costOrNull = (v) => (v === '' || v === null || v === undefined ? null : parseFloat(v));
/* The slabs the GST Council actually levies, since 22 September 2025: 12% and
   28% were abolished and 40% was introduced for sin goods. This list still read
   `[0, 5, 12, 18, 28]`, so the form offered two rates that no longer exist and
   withheld the one that does — a product created today could be born carrying an
   abolished slab, which is precisely what the "Dead Slabs" check exists to find.
   Live count when this was written: 14 of 106 products already carry one. */
const GST_RATES = [0, 5, 18, 40];

/* Abolished, and deliberately still selectable on a product that already has
   one. Removing the option outright would leave the select with no matching
   value, and the browser would show — and on the next save WRITE — a different
   rate than the product actually carries. Silently re-rating somebody's catalogue
   is far worse than showing them a rate that needs fixing, so the old value stays
   visible, labelled as withdrawn, until a person changes it on purpose. */
const ABOLISHED_GST_RATES = [12, 28];

/** Every rate this product may show: the live slabs, plus its own if withdrawn. */
const ratesFor = (current) =>
  ABOLISHED_GST_RATES.includes(current) ? [...GST_RATES, current].sort((a, b) => a - b)
                                        : GST_RATES;

/** The create and edit forms are the same eight fields, so they are one component. */
function ProductFields({ value, onChange }) {
  const set = (k, v) => onChange({ ...value, [k]: v });
  return (
    <div className="gn-form__grid gn-form__grid--2 gn-form__grid--flush">
      <label className="fld">
        <span className="fld__l">Name<span className="fld__req">*</span></span>
        <input className="inp" required value={value.name} onChange={e => set('name', e.target.value)} />
      </label>
      <label className="gn-chk">
        <input type="checkbox" checked={value.is_service} onChange={e => set('is_service', e.target.checked)} />
        <span>This is a service</span>
      </label>
      <label className="fld">
        <span className="fld__l">HSN code</span>
        <input className="inp" placeholder="For goods" value={value.hsn_code} onChange={e => set('hsn_code', e.target.value)} />
      </label>
      <label className="fld">
        <span className="fld__l">SAC code</span>
        <input className="inp" placeholder="For services" value={value.sac_code} onChange={e => set('sac_code', e.target.value)} />
      </label>
      <label className="fld">
        <span className="fld__l">Unit</span>
        <input className="inp" value={value.unit} onChange={e => set('unit', e.target.value)} />
      </label>
      <label className="fld">
        <span className="fld__l">Sale price (₹)</span>
        <input className="inp" type="number" step="0.01" value={value.price} onChange={e => set('price', e.target.value)} />
      </label>
      <label className="fld">
        <span className="fld__l">Cost price (₹)</span>
        <span className="fld__hint">What it costs you. Leave blank if not known.</span>
        <input className="inp" type="number" step="0.01" value={value.cost_price ?? ''}
               onChange={e => set('cost_price', e.target.value)} />
      </label>
      <label className="fld">
        <span className="fld__l">GST rate</span>
        <select className="inp" value={value.gst_rate} onChange={e => set('gst_rate', parseFloat(e.target.value))}>
          {ratesFor(value.gst_rate).map(r => (
            <option key={r} value={r}>
              {r}%{ABOLISHED_GST_RATES.includes(r) ? ' — withdrawn Sep 2025' : ''}
            </option>
          ))}
        </select>
      </label>
      <label className="fld">
        <span className="fld__l">Description</span>
        <input className="inp" value={value.description} onChange={e => set('description', e.target.value)} />
      </label>
    </div>
  );
}

export default function ProductsTab() {
  const { pushToast } = useToast();
  // F32. The module comes from the route, so this tab never names it — the
  // string 'ganit' appearing in ten tab files is ten chances to write the wrong
  // one. `canWrite` is TRUE for org_admin, org_owner and platform staff, so
  // nothing below changes for them.
  const { canWrite, reason: denial } = useModuleWrite({ label: 'change the catalogue' });
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [err, setErr] = useState(null);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ ...BLANK });
  const [saving, setSaving] = useState(false);
  const [editId, setEditId] = useState(null);
  const [editForm, setEditForm] = useState({ ...BLANK });
  const [editSaving, setEditSaving] = useState(false);
  const [confirm, setConfirm] = useState(null);

  const load = useCallback(async () => {
    setErr(null);
    setLoading(true);
    try {
      const r = await api.get('/v1/ganit/products');
      setProducts(rows(r));
    } catch (e) {
      // Not an empty catalogue. "No products yet — add your products" on a
      // failed fetch invites the user to re-enter a catalogue they already have.
      setErr(e);
      setProducts([]);
    } finally { setLoading(false); }
  }, []);

  useEffect(() => { load(); }, [load]);

  async function save(e) {
    e.preventDefault();
    setSaving(true);
    try {
      await api.post('/v1/ganit/products', {
        ...form, price: parseFloat(form.price) || 0, cost_price: costOrNull(form.cost_price),
      });
      pushToast({ title: 'Product created', type: 'success' });
      setShowForm(false);
      setForm({ ...BLANK });
      load();
    } catch (err2) {
      pushToast({ title: err2.response?.data?.detail || 'Could not create the product', type: 'error' });
    } finally { setSaving(false); }
  }

  function startEdit(p) {
    setEditId(p.id);
    setEditForm({
      name: p.name || '', hsn_code: p.hsn_code || '', sac_code: p.sac_code || '',
      unit: p.unit || 'NOS', price: p.price ?? '', cost_price: p.cost_price ?? '',
      gst_rate: p.gst_rate ?? 18,
      description: p.description || '', is_service: !!p.is_service,
    });
  }

  async function saveEdit(e) {
    e.preventDefault();
    setEditSaving(true);
    try {
      await api.patch(`/v1/ganit/products/${editId}`, {
        ...editForm, price: parseFloat(editForm.price) || 0,
        cost_price: costOrNull(editForm.cost_price),
      });
      pushToast({ title: 'Product updated', type: 'success' });
      setEditId(null);
      load();
    } catch (err2) {
      pushToast({ title: err2.response?.data?.detail || 'Could not update the product', type: 'error' });
    } finally { setEditSaving(false); }
  }

  async function remove(p) {
    try {
      await api.delete(`/v1/ganit/products/${p.id}`);
      setProducts(prev => prev.filter(x => x.id !== p.id));
      pushToast({ title: 'Product deleted', type: 'success' });
    } catch {
      pushToast({ title: 'Could not delete the product', type: 'error' });
    }
  }

  const view = useTableView(products, {
    searchKeys: ['name', 'hsn_code', 'sac_code'],
    filters: [{ key: 'unit', label: 'Unit' }, { key: 'gst_rate', label: 'GST' }],
  });
  return (
    <div>
      <div className="gn-bar">
        <span className="gn-bar__sp" />
        <button
          type="button"
          className="btn btn--fill btn--sm"
          onClick={() => setShowForm(v => !v)}
          disabled={!canWrite}
          title={denial || undefined}
        >
          {showForm ? 'Close form' : '+ Add product or service'}
        </button>
      </div>

      {/* `canWrite &&` as well as `showForm`, matching InvoicesTab: the button
          above is not the only way this flag gets set, and a form opened by any
          other path is one the API will refuse on submit. */}
      {showForm && canWrite && (
        <form className="gn-form" onSubmit={save}>
          <h3 className="gn-form__t">New product or service</h3>
          <ProductFields value={form} onChange={setForm} />
          <div className="gn-form__acts">
            <button type="button" className="btn btn--ghost btn--sm" onClick={() => setShowForm(false)}>Cancel</button>
            <button type="submit" className="btn btn--fill btn--sm" disabled={saving}>
              {saving ? 'Saving…' : 'Create'}
            </button>
          </div>
        </form>
      )}

      {loading ? (
        <SkeletonRegion label="Loading products"><SkeletonTable rows={6} columns={6} /></SkeletonRegion>
      ) : err ? (
        <ErrorState kind={errorKind(err)} onRetry={load} />
      ) : products.length === 0 ? (
        <EmptyState
          illustration="generic"
          title={{ en: 'No products yet', hi: 'कोई वस्तु नहीं' }}
          /* A viewer is told what the catalogue is for and why it is empty, but
             is not handed a create button the API will refuse. */
          description={canWrite
            ? 'Add your products and services with their HSN or SAC codes and GST rates. Invoice lines then fill themselves from this catalogue.'
            : `The catalogue holds your products and services with their HSN or SAC codes and GST rates. ${denial}`}
          action={canWrite ? '+ Add product or service' : undefined}
          onAction={canWrite ? () => setShowForm(true) : undefined}
        />
      ) : (
        <div className="tv-card">
        <TableToolbar view={view} label="products" />
        <div className="tbl__wrap">
          <table className="tbl">
            <thead>
              <tr>
                <HeadCell sortKey="name" sort={view.sort} onSort={view.onSort}>Name</HeadCell>
                <HeadCell sortKey="hsn_code" sort={view.sort} onSort={view.onSort}>HSN/SAC</HeadCell>
                <HeadCell sortKey="unit" sort={view.sort} onSort={view.onSort}>Unit</HeadCell>
                <HeadCell sortKey="price" sort={view.sort} onSort={view.onSort} num>Sale</HeadCell>
                <HeadCell sortKey="cost_price" sort={view.sort} onSort={view.onSort} num>Cost</HeadCell>
                <HeadCell sortKey="margin" sort={view.sort} onSort={view.onSort} num>Margin</HeadCell>
                <HeadCell sortKey="gst_rate" sort={view.sort} onSort={view.onSort} num>GST</HeadCell>
                <HeadCell sortKey="is_service" sort={view.sort} onSort={view.onSort}>Type</HeadCell>
                <CreatedHead sort={view.sort} onSort={view.onSort} />
                <th aria-label="Actions" />
              </tr>
            </thead>
            <tbody>
              {view.rows.map(p => (
                <React.Fragment key={p.id}>
                  <tr>
                    <td>
                      {/* The name is a control only because it opens the
                          editor. With no edit to open it is a label, and
                          rendering it as a button would promise one. */}
                      {canWrite ? (
                        <button type="button" className="gn-link" onClick={() => startEdit(p)}>{p.name}</button>
                      ) : p.name}
                    </td>
                    <td className="gn-tbl__mono">{p.hsn_code || p.sac_code || '—'}</td>
                    <td>{p.unit}</td>
                    <td className="tbl__num">{inr(Number(p.price))}</td>
                    <td className="tbl__num">
                      {p.cost_price == null ? '—' : inr(Number(p.cost_price))}
                    </td>
                    <td className="tbl__num">
                      {p.margin == null ? '—' : (
                        <>{inr(Number(p.margin))}{' '}
                          <span className="gn-tbl__mono">
                            ({p.margin_pct == null ? '—' : `${Number(p.margin_pct)}%`})
                          </span>
                        </>
                      )}
                    </td>
                    <td className="tbl__num">{Number(p.gst_rate)}%</td>
                    <td>
                      <Badge
                        text={p.is_service ? 'Service' : 'Goods'}
                        color={p.is_service ? 'var(--st-in-review)' : 'var(--st-in-progress)'}
                      />
                    </td>
                    <CreatedCell value={p.created_at} />
                    <td>
                      <span className="gn-tbl__acts">
                        <button
                          type="button" className="gn-act" onClick={() => startEdit(p)}
                          disabled={!canWrite} title={denial || undefined}
                        >
                          Edit
                        </button>
                        {/* Deleting a catalogue entry that invoices already
                            reference is not obviously reversible, so it asks. */}
                        <button
                          type="button" className="gn-act gn-act--danger"
                          disabled={!canWrite} title={denial || undefined}
                          onClick={() => setConfirm({
                            title: `Delete ${p.name}?`,
                            message: 'The product is removed from the catalogue. Invoices already raised keep their lines.',
                            confirmLabel: 'Delete',
                            onConfirm: () => remove(p),
                          })}
                        >
                          Delete
                        </button>
                      </span>
                    </td>
                  </tr>
                  {editId === p.id && canWrite && (
                    <tr>
                      <td colSpan={10}>
                        <form className="gn-form gn-form--accent" onSubmit={saveEdit}>
                          <h4 className="gn-form__h">Edit {p.name}</h4>
                          <ProductFields value={editForm} onChange={setEditForm} />
                          <div className="gn-form__acts">
                            <button type="button" className="btn btn--ghost btn--sm" onClick={() => setEditId(null)}>Cancel</button>
                            <button type="submit" className="btn btn--fill btn--sm" disabled={editSaving}>
                              {editSaving ? 'Saving…' : 'Save'}
                            </button>
                          </div>
                        </form>
                      </td>
                    </tr>
                  )}
                </React.Fragment>
              ))}
            </tbody>
          </table>
        </div>
        </div>
      )}

      <ConfirmDialog state={confirm} onClose={() => setConfirm(null)} />
    </div>
  );
}
