// Dynamic cover-page variants for the on-demand PDF.
// Same skeleton as PdfCover, but the headline, KPI hint copy, comparison
// baseline, and generation stamp change with the report kind.

// ── shared helpers ─────────────────────────────────────────────────
function StampHeader({ kindLabel, kindHi, period, durationLine, badge }) {
  return (
    <div className="pdf__head pdf__head--ondemand">
      <div className="pdf__brand">
        <span className="pdf__brand-main">Kartavya</span>
        <span className="pdf__brand-hi">कर्तव्य</span>
        <span className="pdf__brand-by">by Aekam Inc</span>
      </div>
      <div className="pdf__head-stamp">
        <span className={'pdf__stamp pdf__stamp--' + (badge || 'ondemand')}>
          {badge === 'auto' ? 'AUTOMATED' : 'ON-DEMAND'}
        </span>
        <div className="pdf__stamp-meta">
          <span>{kindLabel} <i>· {kindHi}</i></span>
          <span>{period}</span>
          {durationLine && <span className="pdf__stamp-dur">{durationLine}</span>}
        </div>
      </div>
    </div>
  );
}

function GenBy({ name, when }) {
  return (
    <div className="pdf__cover-by">
      <span><b>Generated by</b> {name}</span>
      <span className="pdf__cover-by-sep">·</span>
      <span>{when}</span>
    </div>
  );
}

// ── 1. DAILY on-demand cover ───────────────────────────────────────
function PdfCoverDaily() {
  return (
    <div className="pdf">
      <StampHeader
        kindLabel="Daily report"
        kindHi="दैनिक"
        period="Mon 18 May 2026"
      />
      <div className="pdf__body">
        <div className="pdf__cover">
          <div className="pdf__cover-kicker">DAILY · MON 18 MAY 2026 · 14:32 IST</div>
          <h1 className="pdf__cover-h1">
            Today at Aekam<br/>
            so far — <em>10 done</em>, 3 left.
          </h1>
          <div className="pdf__cover-hi">अद्य का प्रतिवेदन</div>

          <div className="pdf__cover-meta">
            <div>
              <div className="pdf__meta-k">As of</div>
              <div className="pdf__meta-v">14:32 IST · live</div>
            </div>
            <div>
              <div className="pdf__meta-k">Scope</div>
              <div className="pdf__meta-v">4 projects · 6 members</div>
            </div>
            <div>
              <div className="pdf__meta-k">Compared to</div>
              <div className="pdf__meta-v">Fri 15 May + 7-day avg</div>
            </div>
            <div>
              <div className="pdf__meta-k">Hours of work left</div>
              <div className="pdf__meta-v">~3.5h to EOD</div>
            </div>
          </div>

          <div className="pdf__kpis">
            <div className="pdf__kpi pdf__kpi--ok">
              <div className="pdf__kpi-k">Completed today</div>
              <div className="pdf__kpi-v">10</div>
              <div className="pdf__kpi-hint">↑ 2 vs Fri · ↑ 1.4 vs 7-day avg</div>
            </div>
            <div className="pdf__kpi">
              <div className="pdf__kpi-k">Due by EOD</div>
              <div className="pdf__kpi-v">3</div>
              <div className="pdf__kpi-hint">2 in progress, 1 in review</div>
            </div>
            <div className="pdf__kpi pdf__kpi--warn">
              <div className="pdf__kpi-k">Awaiting approval</div>
              <div className="pdf__kpi-v">4</div>
              <div className="pdf__kpi-hint">oldest: 2d (KAR-308)</div>
            </div>
            <div className="pdf__kpi pdf__kpi--bad">
              <div className="pdf__kpi-k">Overdue · live</div>
              <div className="pdf__kpi-v">3</div>
              <div className="pdf__kpi-hint">Q1 audit prep × 2</div>
            </div>
          </div>

          <div className="pdf__exec">
            <div className="pdf__exec-h">Today, briefly <span>संक्षेप</span></div>
            <p>
              <b>Solid morning.</b> 10 tasks closed by 14:32 — above the
              7-day rolling average. Mumbai client review is the busy track
              (4 closed). Two approvals on the audit-prep workstream are
              the only blockers right now.
            </p>
            <p>
              <em>Eye on:</em> KAR-308 (BBMP permit packet) has been
              awaiting approval for 2 days — Vikram pinged the approvers
              an hour ago.
            </p>
          </div>

          <GenBy name="Keval Shah · Admin" when="generated on-demand · 18 May 2026 · 14:32 IST" />
        </div>
      </div>
      <div className="pdf__foot">
        <span>aekam_daily_2026-05-18_1432.pdf · live snapshot</span>
        <span>Page 1 / 4</span>
      </div>
    </div>
  );
}

// ── 2. WEEKLY on-demand cover (slight twist on auto) ──────────────
function PdfCoverWeeklyOnDemand() {
  return (
    <div className="pdf">
      <StampHeader
        kindLabel="Weekly report"
        kindHi="साप्ताहिक"
        period="WK 20 · 11–17 May 2026"
      />
      <div className="pdf__body">
        <div className="pdf__cover">
          <div className="pdf__cover-kicker">WEEKLY · WK 20 (11–17 MAY 2026)</div>
          <h1 className="pdf__cover-h1">
            A week of <em>50</em><br/>
            closed tasks.
          </h1>
          <div className="pdf__cover-hi">साप्ताहिक प्रतिवेदन</div>

          <div className="pdf__cover-meta">
            <div>
              <div className="pdf__meta-k">Period</div>
              <div className="pdf__meta-v">11–17 May 2026</div>
            </div>
            <div>
              <div className="pdf__meta-k">Days covered</div>
              <div className="pdf__meta-v">7 (Mon–Sun)</div>
            </div>
            <div>
              <div className="pdf__meta-k">Scope</div>
              <div className="pdf__meta-v">4 projects · 6 members</div>
            </div>
            <div>
              <div className="pdf__meta-k">Compared to</div>
              <div className="pdf__meta-v">WK 19 + 4-week trend</div>
            </div>
          </div>

          <div className="pdf__kpis">
            <div className="pdf__kpi pdf__kpi--ok">
              <div className="pdf__kpi-k">Completed</div>
              <div className="pdf__kpi-v">50</div>
              <div className="pdf__kpi-hint">↑ 14% WoW · ↑ 8% vs 4-wk avg</div>
            </div>
            <div className="pdf__kpi">
              <div className="pdf__kpi-k">Due this week</div>
              <div className="pdf__kpi-v">41</div>
              <div className="pdf__kpi-hint">closes Sun 17 May</div>
            </div>
            <div className="pdf__kpi pdf__kpi--warn">
              <div className="pdf__kpi-k">Awaiting</div>
              <div className="pdf__kpi-v">9</div>
              <div className="pdf__kpi-hint">oldest: 5d</div>
            </div>
            <div className="pdf__kpi pdf__kpi--bad">
              <div className="pdf__kpi-k">Overdue</div>
              <div className="pdf__kpi-v">8</div>
              <div className="pdf__kpi-hint">↓ 2 WoW · best in 5 weeks</div>
            </div>
          </div>

          {/* 4-week mini sparkline — extra context not in the auto version */}
          <div className="pdf-cv__trend">
            <div className="pdf-cv__trend-h">
              4-week completion trend <span>चार सप्ताह</span>
            </div>
            <div className="pdf-cv__bars">
              {[
                { w: 'WK 17', n: 38 }, { w: 'WK 18', n: 42 },
                { w: 'WK 19', n: 44 }, { w: 'WK 20', n: 50, here: true },
              ].map((d, i) => (
                <div key={i} className={'pdf-cv__bar' + (d.here ? ' is-here' : '')}>
                  <div className="pdf-cv__bar-col" style={{ height: d.n * 1.6 + 'px' }} />
                  <div className="pdf-cv__bar-lbl">{d.w}</div>
                  <div className="pdf-cv__bar-n">{d.n}</div>
                </div>
              ))}
            </div>
          </div>

          <GenBy name="Keval Shah · Admin" when="generated on-demand · 18 May 2026 · 11:42 IST" />
        </div>
      </div>
      <div className="pdf__foot">
        <span>aekam_weekly_wk20_2026.pdf · on-demand</span>
        <span>Page 1 / 5</span>
      </div>
    </div>
  );
}

// ── 3. MONTHLY on-demand cover ─────────────────────────────────────
function PdfCoverMonthly() {
  return (
    <div className="pdf">
      <StampHeader
        kindLabel="Monthly report"
        kindHi="मासिक"
        period="April 2026"
      />
      <div className="pdf__body">
        <div className="pdf__cover">
          <div className="pdf__cover-kicker">MONTHLY · APRIL 2026 · FY26 Q1</div>
          <h1 className="pdf__cover-h1">
            April in review.<br/>
            <em>219 tasks</em> shipped.
          </h1>
          <div className="pdf__cover-hi">मासिक प्रतिवेदन</div>

          <div className="pdf__cover-meta">
            <div>
              <div className="pdf__meta-k">Period</div>
              <div className="pdf__meta-v">1–30 April 2026</div>
            </div>
            <div>
              <div className="pdf__meta-k">Quarter</div>
              <div className="pdf__meta-v">FY26 Q1 · month 1 of 3</div>
            </div>
            <div>
              <div className="pdf__meta-k">Scope</div>
              <div className="pdf__meta-v">5 projects · 6 members</div>
            </div>
            <div>
              <div className="pdf__meta-k">Compared to</div>
              <div className="pdf__meta-v">March + Q4 FY25 monthly avg</div>
            </div>
          </div>

          <div className="pdf__kpis">
            <div className="pdf__kpi pdf__kpi--ok">
              <div className="pdf__kpi-k">Completed</div>
              <div className="pdf__kpi-v">219</div>
              <div className="pdf__kpi-hint">↑ 22% MoM · strongest mo. FY26</div>
            </div>
            <div className="pdf__kpi pdf__kpi--ok">
              <div className="pdf__kpi-k">Cycle time</div>
              <div className="pdf__kpi-v">2.4d</div>
              <div className="pdf__kpi-hint">↓ 0.6d MoM</div>
            </div>
            <div className="pdf__kpi">
              <div className="pdf__kpi-k">Approvals</div>
              <div className="pdf__kpi-v">38</div>
              <div className="pdf__kpi-hint">median: 4h · best in 6 mo.</div>
            </div>
            <div className="pdf__kpi pdf__kpi--warn">
              <div className="pdf__kpi-k">Overdue rate</div>
              <div className="pdf__kpi-v">3.6%</div>
              <div className="pdf__kpi-hint">↓ from 5.8% in March</div>
            </div>
          </div>

          {/* 4 weekly bars — month-arc */}
          <div className="pdf-cv__trend">
            <div className="pdf-cv__trend-h">
              Weekly completion — April <span>साप्ताहिक</span>
            </div>
            <div className="pdf-cv__bars pdf-cv__bars--wide">
              {[
                { w: 'WK 14', n: 44 }, { w: 'WK 15', n: 58 },
                { w: 'WK 16', n: 49 }, { w: 'WK 17', n: 68, here: true },
              ].map((d, i) => (
                <div key={i} className={'pdf-cv__bar' + (d.here ? ' is-here' : '')}>
                  <div className="pdf-cv__bar-col" style={{ height: d.n * 1.3 + 'px' }} />
                  <div className="pdf-cv__bar-lbl">{d.w}</div>
                  <div className="pdf-cv__bar-n">{d.n}</div>
                </div>
              ))}
            </div>
          </div>

          <div className="pdf__exec" style={{ marginTop: 4 }}>
            <p>
              <b>April closed strong.</b> Last full week (WK 17) was the
              highest-throughput week of the fiscal year so far. Two
              compliance milestones landed on time — GSTR-3B and the
              Saraswati onboarding sign-off. Watch-list for May: Q1 audit
              prep needs a capacity boost before the 22 May deadline.
            </p>
          </div>

          <GenBy name="Keval Shah · Admin" when="generated on-demand · 18 May 2026 · 11:42 IST" />
        </div>
      </div>
      <div className="pdf__foot">
        <span>aekam_monthly_2026-04.pdf · on-demand</span>
        <span>Page 1 / 7</span>
      </div>
    </div>
  );
}

// ── 4. CUSTOM range on-demand cover ────────────────────────────────
function PdfCoverCustom() {
  return (
    <div className="pdf">
      <StampHeader
        kindLabel="Custom range"
        kindHi="अनुकूल अवधि"
        period="11 Apr – 12 May 2026"
        durationLine="32 days · spans April + May"
      />
      <div className="pdf__body">
        <div className="pdf__cover">
          <div className="pdf__cover-kicker">CUSTOM RANGE · 32 DAYS</div>
          <h1 className="pdf__cover-h1">
            <em>32 days</em> at Aekam<br/>
            — 11 Apr to 12 May.
          </h1>
          <div className="pdf__cover-hi">अनुकूल प्रतिवेदन</div>

          <div className="pdf__cover-meta">
            <div>
              <div className="pdf__meta-k">From</div>
              <div className="pdf__meta-v">Sat 11 Apr 2026</div>
            </div>
            <div>
              <div className="pdf__meta-k">To</div>
              <div className="pdf__meta-v">Tue 12 May 2026</div>
            </div>
            <div>
              <div className="pdf__meta-k">Calendar</div>
              <div className="pdf__meta-v">22 weekdays · 10 weekend days</div>
            </div>
            <div>
              <div className="pdf__meta-k">Compared to</div>
              <div className="pdf__meta-v">prior 32 days · 10 Mar – 10 Apr</div>
            </div>
          </div>

          <div className="pdf__kpis">
            <div className="pdf__kpi pdf__kpi--ok">
              <div className="pdf__kpi-k">Completed</div>
              <div className="pdf__kpi-v">186</div>
              <div className="pdf__kpi-hint">↑ 17% vs prior 32d</div>
            </div>
            <div className="pdf__kpi">
              <div className="pdf__kpi-k">Avg per weekday</div>
              <div className="pdf__kpi-v">8.5</div>
              <div className="pdf__kpi-hint">peak: 14 (Thu 24 Apr)</div>
            </div>
            <div className="pdf__kpi pdf__kpi--warn">
              <div className="pdf__kpi-k">Awaiting</div>
              <div className="pdf__kpi-v">12</div>
              <div className="pdf__kpi-hint">at end of range</div>
            </div>
            <div className="pdf__kpi pdf__kpi--bad">
              <div className="pdf__kpi-k">Overdue</div>
              <div className="pdf__kpi-v">9</div>
              <div className="pdf__kpi-hint">↓ 4 vs prior 32d</div>
            </div>
          </div>

          {/* Range timeline — visual cue that the range spans 2 months */}
          <div className="pdf-cv__range">
            <div className="pdf-cv__range-h">
              Range timeline <span>समय रेखा</span>
            </div>
            <div className="pdf-cv__rail">
              <div className="pdf-cv__rail-band" />
              <div className="pdf-cv__rail-mark" style={{ left: '0%' }}>
                <i/><span>11 Apr</span>
              </div>
              <div className="pdf-cv__rail-mark pdf-cv__rail-mark--mid" style={{ left: '63%' }}>
                <i/><span>1 May</span>
                <small>month boundary</small>
              </div>
              <div className="pdf-cv__rail-mark pdf-cv__rail-mark--end" style={{ left: '100%' }}>
                <i/><span>12 May</span>
              </div>
              <div className="pdf-cv__rail-shade pdf-cv__rail-shade--a" style={{ left: '0%',  width: '63%' }}><b>April</b><small>20 days</small></div>
              <div className="pdf-cv__rail-shade pdf-cv__rail-shade--b" style={{ left: '63%', width: '37%' }}><b>May</b><small>12 days</small></div>
            </div>
            <div className="pdf-cv__range-note">
              Range covers <b>20 days of April</b> and <b>12 days of May</b>.
              Cross-month comparisons in this report use the prior 32-day
              window, not the calendar month boundaries.
            </div>
          </div>

          <GenBy name="Keval Shah · Admin" when="generated on-demand · 18 May 2026 · 11:42 IST" />
        </div>
      </div>
      <div className="pdf__foot">
        <span>aekam_custom_20260411-20260512.pdf · on-demand</span>
        <span>Page 1 / 5</span>
      </div>
    </div>
  );
}

Object.assign(window, { PdfCoverDaily, PdfCoverWeeklyOnDemand, PdfCoverMonthly, PdfCoverCustom });
